/**
 * Enumeraciones usadas para los errores del ms
 * @author Gabriel Garzon
 */

export enum EMessageErrorGeneral {
    READ_JSON = "ERROR EN LA TRANSAFORMACION DE LINEA DEL JSON DE FEATURES",
    DOWNLOAD_PRICES = "ERROR EN LA DESCARGA Y TRANSAFORMACION ",
    SAVE_FILE_DB = "ERROR EN EL GUARDADO DE DATA EN LA BASE DE DATOS",
    TRANFORM_PRICES = "ERROR EN LA TRANSFORMACION DE DATOS",
    TRANFORM_PRICES_TECHNOLOOGY = "ERROR EN LA TRANSFORMACION DE PRECIOS - TECNOLOGIA",
    DOWNLOAD_FILE = "ERROR EN LA DESCARGA POR MEDIO DEL SFTP",
    DOWNLOAD_DATA_MOVIL = "ERROR EN LA DESCARGA DE INFORMACION",
    TRANFORM_PRICES_MOVIL = "ERROR EN LA TRANSFORMACION DE PRECIOS - MOVIL",
    TRANFORM_FEATURES_MOVIL = "ERROR EN LA TRANSFORMACION DE CARACTERISTICAS - MOVIL",
    CONEXION_ERROR_DB_SP = "ERROR DE CONEXION A LA BASE DE DATOS",
    WRITE_FILE ="ERROR ESCRIBIENDO ARCHIVO VOLCADO",
    FIND_CARACTERISTICAS = "ERROR CONSULTANDO CARACTERISTICAS CON DISPONIBILIDAD",
    ERROR_SAVE_DATA='ERROR GUARDANDO DATA',
}