import { GeographicAddressListDTO } from 'src/controller/dto/hompass/geographicAddressList.dto';
import {
  EAccountType,
  EBilling,
  EProcSales,
  ETypeDelivery,
  ETypePayment,
  ETypePlan,
  ETypeProduct,
  ETypeSales,
  EstateTransaction,
  EtypeDocument,
  StateHHPP,
} from '../src/common/utils/enums/params.enum';
import { GeographicAddressDTO } from 'src/controller/dto/structures/geographicAddress.dto';
import { GeographicAddressListDto } from 'src/controller/dto/geographicAddres/geographicAddressList/geographicAddressList.dto';
import { StructuresDTO } from 'src/controller/dto/structures/structures.dto';

const homepass_response = {
  process: '04561ae0-e5d5-11ed-824c-4f4e5abfa51a',
  success: true,
  status: 200,
  documents: {
    geographicAddress: {
      igacAddress: 'CL 75 12 70',
      latitudeCoordinate: '4.66131837',
      lengthCoordinate: '-74.05870882',
      strata: '1',
      splitAddress: {
        type: 'CK',
        streetAlt: 'P',
        neighborhood: null,
        streetType: 'CALLE',
        streetNr: '75',
        streetSuffix: null,
        streetNlPostViaP: null,
        streetBis: null,
        streetBlockGenerator: null,
        streetTypeGenerator: null,
        streetNrGenerator: '12',
        streetLtGenerator: null,
        streetNlPostViaG: null,
        streetBisGenerator: null,
        streetName: null,
        addressPlate: '70',
        complement: {
          nivel1Type: null,
          nivel2Type: null,
          nivel3Type: null,
          nivel4Type: null,
          nivel5Type: 'CASA',
          nivel6Type: null,
          nivel1Value: null,
          nivel2Value: null,
          nivel3Value: null,
          nivel4Value: null,
          nivel5Value: null,
          nivel6Value: null,
        },
        alternateGeographicAddress: {
          nivel1Type: null,
          nivel2Type: null,
          nivel3Type: null,
          nivel4Type: null,
          nivel5Type: null,
          nivel6Type: null,
          nivel1Value: null,
          nivel2Value: null,
          nivel3Value: null,
          nivel4Value: null,
          nivel5Value: null,
          nivel6Value: null,
        },
        plateTypeLt: null,
        plateValueLt: null,
        cadastreId: 'd2079',
        geoState: 'D',
      },
      listCover: [
        {
          technology: 'BI',
          node: '3B4023',
          state: 'ACT',
          qualificationDate: '2018/12/04',
        },
        {
          technology: 'FOG',
          node: 'GPON 15706',
          state: '',
          qualificationDate: '',
        },
        {
          technology: 'DTH',
          node: 'HCHICB',
          state: 'ACT',
          qualificationDate: '2018/12/04',
        },
        {
          technology: 'MOV',
          node: 'BOG.Sergio Arboleda',
          state: '',
          qualificationDate: '',
        },
        {
          technology: 'LTE',
          node: 'Viable_LTE',
          state: '',
          qualificationDate: '',
        },
      ],
      listHhpps: [
        {
          id: 2079,
          idQualificationTechnologyType: '',
          rushCblType: 'CAJA RELIANCE',
          state: 'CS',
          technology: 'BI',
          nodes: {
            node: {
              nodeId: '',
              state: 'ACT',
              qualificationDate: '2018/12/04',
              nodeName: 'UNIVERSIDAD 6                ',
              technology: 'BI',
            },
          },
        },
      ],
    },
  },
  message: 'En la dirección ingresada se encuentra instalado un servicio Claro.',
  requestTime: '2023-04-28T14:57:38+00:00',
  responseTime: 4004,
  method: 'POST',
  origen: '/RSServicehomepass/v1/coverage/homepass',
};

const homepass_request = {
  isMigratedUser: false,
  transactionId: '18327983',
  ip: '10.2.192.2',
  daneCode: '11001000',
  address: 'CL 75 12 70',
  isDth: 'true',
  managementNode: 'node',
  user: 'user258',
  strata: '1',
  geographicAddressList: {
    geographicAddress: [
      {
        type: 'CK',
        streetType: 'CALLE',
        streetNr: '75',
        streetSuffix: '',
        streetName: '',
        streetNrGenerator: '12',
        streetTypeGenerator: '',
        streetLtGenerator: '',
        streetBisGenerator: '',
        streetBlockGenerator: '',
        plate: '70',
        streetAlt: '',
        neighborhood: '',
        streetLt: '',
        streetNlPostViaP: '',
        streetBis: '',
        streetBlock: '',
        streetNlPostViaG: '',
        complements: {
          nivel1Type: '',
          nivel2Type: '',
          nivel3Type: '',
          nivel4Type: '',
          nivel5Type: 'CASA',
          nivel6Type: '',
          nivel1Value: '',
          nivel2Value: '',
          nivel3Value: '',
          nivel4Value: '',
          nivel5Value: '',
          nivel6Value: '',
        },
        alternateGeographicAddress: {
          nivel1Type: '',
          nivel2Type: '',
          nivel3Type: '',
          nivel4Type: '',
          nivel5Type: '',
          nivel6Type: '',
          nivel1Value: '',
          nivel2Value: '',
          nivel3Value: '',
          nivel4Value: '',
          nivel5Value: '',
          nivel6Value: '',
        },
        cadastreId: 'd2079',
        plateValueLt: '',
        plateTypeLt: '',
        geoState: 'D',
        idDetailAddress: '',
        word3G: '',
      },
    ],
  },
};

export const structures_request = {
  geographicAddressList: {
    geographicAddress: {
      daneCode: 66682000,
      neighborhood: 'LOS BLOQUES',
      addressType: 'BM',
    },
    complements: {},
    alternateGeographicAddress: {},
    plateTypeIt: '',
    plateValueIt: '',
  },
};

export const structures_response = {
  process: 'fa45cd60-e8fa-11ed-a40a-5d8eb563a2a6',
  success: true,
  status: 200,
  documents: [
    {
      geographicAddressList: {
        geographicAddress: [
          {
            id: '',
            alternateGeographicAddress: [
              {
                nivel4Type: 'MANZANA',
                nivel4Value: 'A,C,E,G,I,K',
              },
            ],
            complements: '',
            plateTypeIt: '',
            plateValueIt: '',
            detailId: '',
            strata: '',
            textAddress: '',
          },
        ],
      },
    },
  ],
  message: 'Execution successfull',
  requestTime: '2023-05-02T15:06:55+00:00',
  responseTime: 21539,
  method: 'POST',
  origen: '/RSServicehomepass/V1/Coverage/structures',
};

export const mockUpdateDB = {
  address: [
    {
      isMigratedUser: false,
      transactionId: '18327983',
      ip: '10.2.192.2',
      daneCode: '11001000',
      address: 'KR 2 ESTE 70 A 86  AP 501',
      isDth: 'true',
      managementNode: 'node',
      user: 'user258',
      strata: '1',
      geographicAddressList: {
        geographicAddress: [
          {
            type: 'CK',
            streetType: 'CARRERA',
            streetNr: '2',
            streetSuffix: '',
            streetName: 'ESTE',
            streetNrGenerator: '70',
            streetTypeGenerator: '',
            streetLtGenerator: 'A',
            streetBisGenerator: '',
            streetBlockGenerator: '',
            plate: '86',
            streetAlt: '',
            neighborhood: 'LAS ACACIAS',
            streetLt: '',
            streetNlPostViaP: '',
            streetBis: '',
            streetBlock: '',
            streetNlPostViaG: '',
            complements: {
              nivel1Type: '',
              nivel2Type: '',
              nivel3Type: '',
              nivel4Type: '',
              nivel5Type: 'APARTAMENTO',
              nivel6Type: '',
              nivel1Value: '',
              nivel2Value: '',
              nivel3Value: '',
              nivel4Value: '',
              nivel5Value: '501',
              nivel6Value: '',
            },
            alternateGeographicAddress: {
              nivel1Type: '',
              nivel2Type: '',
              nivel3Type: '',
              nivel4Type: '',
              nivel5Type: '',
              nivel6Type: '',
              nivel1Value: '',
              nivel2Value: '',
              nivel3Value: '',
              nivel4Value: '',
              nivel5Value: '',
              nivel6Value: '',
            },
            cadastreId: 's3240083',
            plateValueLt: '',
            plateTypeLt: '',
            geoState: 'Y',
            idDetailAddress: '',
            word3G: '',
          },
        ],
      },
    },
  ],
};

export const consumerLegadoRest = {
  executed: true,
  status: 200,
  data: {
    headerResponse: {
      responseDate: '2023-05-05T17:06:44.576-05:00',
      traceabilityId: '87281e28-8fcf-4e20-a45b-13c008f1ea15',
    },
    message: 'Ya existe una solicitud en curso que se encuentra PENDIENTE. de barrio abierto.',
    messageType: 'E',
  },
  message: 'OK',
  requestInfo: {
    url: 'http://100.126.21.189:7777/Address/V2.1/Rest/crearSolicitudInspira',
    method: 'put',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      requestStartedAt: 1683324600427,
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 1539,
      processingTime: 9455,
    },
    params: undefined,
    data: '{"headerRequest":{"requestDate":"2008-09-28T20:49:45"},"user":"hectorg","cmtRequestCrearSolicitudInspira":{"observaciones":"prueba crear solicitud diferente de DTH","contacto":"AnaFernandez Clower","telefonoContacto":"3002323232","canalVentas":"EC9_B2C","drDireccion":{"barrio":"LAS ACACIAS","barrioTxtBM":"LAS ACACIAS","bisViaGeneradora":"","bisViaPrincipal":"","cpTipoNivel1":"","cpTipoNivel2":"","cpTipoNivel3":"","cpTipoNivel4":"","cpTipoNivel5":"APARTAMENTO","cpTipoNivel6":"","cpValorNivel1":"","cpValorNivel2":"","cpValorNivel3":"","cpValorNivel4":"","cpValorNivel5":"501","cpValorNivel6":"","cuadViaGeneradora":"","cuadViaPrincipal":"","dirEstado":"HHPP NO EXISTE","dirPrincAlt":"","estadoDirGeo":"Y","estadoRegistro":0,"estrato":"4","fechaCreacion":"","fechaEdicion":"","id":"3722370","idDirCatastro":"s3240083","idSolicitud":"","idTipoDireccion":"CK","itTipoPlaca":"","itValorPlaca":"","ltViaGeneradora":"A","ltViaPrincipal":"","mzTipoNivel1":"","mzTipoNivel2":"","mzTipoNivel3":"","mzTipoNivel4":"","mzTipoNivel5":"","mzTipoNivel6":"","mzValorNivel1":"","mzValorNivel2":"","mzValorNivel3":"","mzValorNivel4":"","mzValorNivel5":"","mzValorNivel6":"","nlPostViaG":"","nlPostViaP":"","numViaGeneradora":"70","numViaPrincipal":"2","perfilCreacion":"","perfilEdicion":"","placaDireccion":"86","tipoViaGeneradora":"","tipoViaPrincipal":"CARRERA","usuarioCreacion":"","usuarioEdicion":""},"cmtCityEntityDto":{"estratoDir":"4","estadoDir":"HHPP NO EXISTE"}},"tipoTecnologia":"MOV","codigoDane":"73001000","idCasoTcrm":"ECOM-9362706851"}',
    timeout: 15000,
    source: '/Address/V2.1/Rest/crearSolicitudInspira',
  },
};

export const mockPutClientHomePass = {
  customer: {
    isMigratedUser: false,
    user: 'hectorg',
    ip: '191.25.01.172',
    requestDate: undefined,
    customerInfo: {
      id: '1029818201',
      idType: EtypeDocument.CC,
      firstname: 'Ana',
      lastname: 'Fernandez Clower',
      mediumCharacteristic: {
        emailAddress: 'Lpinzon@gmail.com.co',
        phoneNumber: '3002323232',
        idCaseTcrm: 'ECOM-9362706851',
      },
      scId: '102910',
      transactionIdentity: '109219810',
      profileCustomerId: '109219810',
      agreementRef: {
        eBilling: EBilling.S,
      },
      orderRefList: [
        {
          orderRef: {
            id: '0',
            date: undefined,
            subOrderRefList: [
              {
                subOrderRef: {
                  id: '0',
                  salesProcess: EProcSales.HOG,
                  productType: ETypeProduct.Claro,
                  planType: ETypePlan.POS,
                  salesType: ETypeSales.ACT,
                  deliveryType: ETypeDelivery.D,
                  paymentMethodRef: {
                    id: ETypePayment.CON,
                  },
                  accountRef: {
                    id: '102919201012',
                    type: EAccountType.M,
                  },
                  productRefList: undefined,
                  shippingRef: {
                    daneCodeCity: '73001000',
                    city: 'BOGOTA',
                    daneCodeProvince: '21',
                    province: 'CUNDINAMARCA',
                    villageCenterDaneCode: '21000100',
                    villageCenter: 'Suba',
                    neighborhood: 'Subachoque',
                    address: 'Calle 112 # 23-12',
                    region: 'Norte',
                    addressId: '21',
                    strata: '4',
                    technology: 'MOV',
                  },
                },
              },
            ],
          },
        },
      ],
    },
  },
};

export const mocki = {
  customer: {
    isMigratedUser: false,
    user: 'hectorg',
    ip: '191.25.01.172',
    requestDate: '2008-09-28T20:49:45',
    customerInfo: {
      id: '1029818201',
      idType: 'CC',
      firstname: 'Ana',
      lastname: 'Fernandez Clower',
      mediumCharacteristic: {
        emailAddress: 'Lpinzon@gmail.com.co',
        phoneNumber: '3002323232',
        idCaseTcrm: 'ECOM-9362706851',
      },
      scId: '102910',
      transactionIdentity: '109219810',
      profileCustomerId: '109219810',
      agreementRef: {
        eBilling: 'S',
      },
      orderRefList: [
        {
          orderRef: {
            id: '0',
            date: '8/4/2020',
            subOrderRefList: [
              {
                subOrderRef: {
                  id: '0',
                  salesProcess: 'HOG',
                  productType: 'Claro',
                  planType: 'POS',
                  salesType: 'ACT',
                  deliveryType: 'ID',
                  paymentMethodRef: {
                    id: 'CON',
                  },
                  accountRef: {
                    id: '102919201012',
                    type: EAccountType.M,
                  },
                  productRefList: [
                    {
                      productRef: {
                        planId: 'PO_IntPosPlanFtthA100',
                        planDescription: 'Internet 100 MB FTTH',
                        price: '6000',
                        nonTaxPrice: '1200',
                        totalPrice: '4000',
                        taxInd: 'OTT01',
                        itemRefList: [
                          {
                            itemRef: {
                              id: 'PO_IntPosPlanFtthA100',
                              parentId: 'PO_IntPosPlanFtthA100',
                              serviceName: 'PO_IntPosPlanFtthA100',
                            },
                          },
                        ],
                      },
                    },
                  ],
                  shippingRef: {
                    technology: 'MOV',
                    daneCodeCity: '73001000',
                    city: 'BOGOTA',
                    daneCodeProvince: '21',
                    province: 'CUNDINAMARCA',
                    villageCenterDaneCode: '21000100',
                    villageCenter: 'Suba',
                    neighborhood: 'Subachoque',
                    address: 'Calle 112 # 23-12',
                    region: 'Norte',
                    addressId: '21',
                    strata: '4',
                  },
                },
              },
            ],
          },
        },
      ],
    },
  },
};

export const complementsToSegment = [
  [
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'MANZANA',
    'A',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
  ],
  [
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'MANZANA',
    'C',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
  ],
  [
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'MANZANA',
    'E',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
  ],
  [
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'MANZANA',
    'G',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
  ],
  [
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'MANZANA',
    'I',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
  ],
  [
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'MANZANA',
    'K',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
  ],
];

export const alternateGeographicToSegment1 = [
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'A'],
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'C'],
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'E'],
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'G'],
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'I'],
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'K'],
];

export const alternateGeographicToSegment2 = [
  ['OTRO', 'OTRO', 'CALLE', 'A', 'OTRO', 'OTRO', 'MANZANA', 'A'],
  ['OTRO', 'OTRO', 'CALLE', 'B', 'OTRO', 'OTRO', 'MANZANA', 'C'],
  ['OTRO', 'OTRO', 'CALLE', 'C', 'OTRO', 'OTRO', 'MANZANA', 'E'],
  ['OTRO', 'OTRO', 'CALLE', 'D', 'OTRO', 'OTRO', 'MANZANA', 'G'],
  ['OTRO', 'OTRO', 'CALLE', 'E', 'OTRO', 'OTRO', 'MANZANA', 'I'],
  ['OTRO', 'OTRO', 'CALLE', 'F', 'OTRO', 'OTRO', 'MANZANA', 'K'],
];

export const alternateGeographicToSegment3 = [
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'CALLE', 'A'],
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'CALLE', 'B'],
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'CALLE', 'C'],
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'G'],
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'I'],
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'K'],
];

export const alternateGeographicToSegment4 = [
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'CALLE', 'A'],
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'B'],
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'CARRERA', 'C'],
  ['CASA', 'A', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO'],
];

export const alternateGeographicToSegment5 = [
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'CALLE', 'A'],
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'B'],
  ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'CARRERA', 'C'],
];

export const legadoRequest = { outBinds: { po_codigo: -3, po_descripcion: 'a' } };

export const mockAddressComplementUCRequest = {
  geographicAddressList: {
    geographicAddress: {
      addressType: 'CK',
      id: '3784805',
    },
    alternateGeographicAddress: {
      nivel1Type: '',
      nivel2Type: '',
      nivel3Type: '',
      nivel4Type: '',
      nivel5Type: '',
      nivel6Type: '',
      nivel1Value: '',
      nivel2Value: '',
      nivel3Value: '',
      nivel4Value: '',
      nivel5Value: '',
      nivel6Value: '',
    },
    complements: {
      nivel1Type: 'BLOQUE',
      nivel1Value: '3',
      nivel2Type: '',
      nivel3Type: '',
      nivel4Type: '',
      nivel6Type: '',
      nivel2Value: '',
      nivel3Value: '',
      nivel4Value: '',
      nivel6Value: '',
      nivel5Type: 'APARTAMENTO',
      nivel5Value: '502',
    },
    plateTypeIt: '',
    plateValueIt: '',
  },
};

export const mockRequestAddressComplementResponse = {
  '0': [
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'BLOQUE',
    '3',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'APARTAMENTO',
    '502',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    9608663,
    'KR 8 62 31 BQ 3 AP 502',
    5129631,
    -1,
    'P',
    'LAS CEIBAS',
    'CARRERA',
    '8',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    '62',
    'OTRO',
    'OTRO',
    'OTRO',
    'OTRO',
    '31',
    'OTRO',
    'OTRO',
    'OTRO',
  ],
};

export const MockHomepassRetryReq = {
  address: [
    {
      isMigratedUser: false,
      transactionId: '18327983',
      ip: '10.2.192.2',
      daneCode: '11001000',
      address: 'KR 2 ESTE 70 A 86  AP 501',
      isDth: 'true',
      managementNode: 'node',
      user: 'user258',
      strata: '1',
      geographicAddressList: {
        geographicAddress: [
          {
            type: 'CK',
            streetType: 'CARRERA',
            streetNr: '2',
            streetSuffix: '',
            streetName: 'ESTE',
            streetNrGenerator: '70',
            streetTypeGenerator: '',
            streetLtGenerator: 'A',
            streetBisGenerator: '',
            streetBlockGenerator: '',
            plate: '86',
            streetAlt: '',
            neighborhood: 'LAS ACACIAS',
            streetLt: '',
            streetNlPostViaP: '',
            streetBis: '',
            streetBlock: '',
            streetNlPostViaG: '',
            complements: {
              nivel1Type: '',
              nivel2Type: '',
              nivel3Type: '',
              nivel4Type: '',
              nivel5Type: 'APARTAMENTO',
              nivel6Type: '',
              nivel1Value: '',
              nivel2Value: '',
              nivel3Value: '',
              nivel4Value: '',
              nivel5Value: '501',
              nivel6Value: '',
            },
            alternateGeographicAddress: {
              nivel1Type: '',
              nivel2Type: '',
              nivel3Type: '',
              nivel4Type: '',
              nivel5Type: '',
              nivel6Type: '',
              nivel1Value: '',
              nivel2Value: '',
              nivel3Value: '',
              nivel4Value: '',
              nivel5Value: '',
              nivel6Value: '',
            },
            cadastreId: 's3240083',
            plateValueLt: '',
            plateTypeLt: '',
            geoState: 'Y',
            idDetailAddress: '',
            word3G: '',
          },
        ],
      },
    },
  ],
  cmtRequestCrearSolicitud: [
    {
      customer: {
        isMigratedUser: false,
        user: 'hectorg',
        ip: '191.25.01.172',
        requestDate: '2008-09-28T20:49:45',
        customerInfo: {
          id: '1029818201',
          idType: 'CC',
          firstname: 'Ana',
          lastname: 'Fernandez Clower',
          mediumCharacteristic: {
            emailAddress: 'Lpinzon@gmail.com.co',
            phoneNumber: '3002323232',
            idCaseTcrm: 'ECOM-9362706851',
          },
          scId: '102910',
          transactionIdentity: '109219810',
          profileCustomerId: '109219810',
          agreementRef: {
            eBilling: 'S',
          },
          orderRefList: [
            {
              orderRef: {
                id: '0',
                date: '8/4/2020',
                subOrderRefList: [
                  {
                    subOrderRef: {
                      id: '0',
                      salesProcess: 'HOG',
                      productType: 'Claro',
                      planType: 'POS',
                      salesType: 'ACT',
                      deliveryType: 'ID',
                      paymentMethodRef: {
                        id: 'CON',
                      },
                      accountRef: {
                        id: '102919201012',
                        type: 'M',
                      },
                      productRefList: [
                        {
                          productRef: {
                            planId: 'PO_IntPosPlanFtthA100',
                            planDescription: 'Internet 100 MB FTTH',
                            price: '6000',
                            nonTaxPrice: '1200',
                            totalPrice: '4000',
                            taxInd: 'OTT01',
                            itemRefList: [
                              {
                                itemRef: {
                                  id: 'PO_IntPosPlanFtthA100',
                                  parentId: 'PO_IntPosPlanFtthA100',
                                  serviceName: 'PO_IntPosPlanFtthA100',
                                },
                              },
                            ],
                          },
                        },
                      ],
                      shippingRef: {
                        technology: 'MOV',
                        daneCodeCity: '73001000',
                        city: 'BOGOTA',
                        daneCodeProvince: '21',
                        province: 'CUNDINAMARCA',
                        villageCenterDaneCode: '21000100',
                        villageCenter: 'Suba',
                        neighborhood: 'Subachoque',
                        address: 'Calle 112 # 23-12',
                        region: 'Norte',
                        addressId: '21',
                        strata: '4',
                      },
                    },
                  },
                ],
              },
            },
          ],
        },
      },
    },
  ],
};

export const legadoRestReq = {
  data: { messageType: 'I', estado: 'EMPEZADO' },
};

export const legadoRestReq2 = {
  executed: true,
  type: 'cmtAddressGeneralResponseDto',
  message: 'No se encontro ninguna dirección con los criterios de busqueda ingresados',
  messageType: 'I',
  idCentroPoblado: '24926',
  centroPoblado: 'BOGOTA',
  listAddresses: [],
  data: { messageType: 'I', estado: EstateTransaction.INICIADO, resultado: StateHHPP.HHPP_CREADO },
};

export const elementNeeded = [
  {
    cmtRequestCrearSolicitud: [
      {
        customer: {
          isMigratedUser: false,
          user: 'hectorg',
          ip: '191.25.01.172',
          requestDate: '2008-09-28T20:49:45',
          customerInfo: {
            id: '1029818201',
            idType: 'CC',
            firstname: 'Ana',
            lastname: 'Fernandez Clower',
            mediumCharacteristic: {
              emailAddress: 'Lpinzon@gmail.com.co',
              phoneNumber: '3002323232',
              idCaseTcrm: 'ECOM-9362706851',
            },
            scId: '102910',
            transactionIdentity: '109219810',
            profileCustomerId: '109219810',
            agreementRef: {
              eBilling: 'S',
            },
            orderRefList: [
              {
                orderRef: {
                  id: '0',
                  date: '8/4/2020',
                  subOrderRefList: [
                    {
                      subOrderRef: {
                        id: '0',
                        salesProcess: 'HOG',
                        productType: 'Claro',
                        planType: 'POS',
                        salesType: 'ACT',
                        deliveryType: 'ID',
                        paymentMethodRef: {
                          id: 'CON',
                        },
                        accountRef: {
                          id: '102919201012',
                          type: 'M',
                        },
                        productRefList: [
                          {
                            productRef: {
                              planId: 'PO_IntPosPlanFtthA100',
                              planDescription: 'Internet 100 MB FTTH',
                              price: '6000',
                              nonTaxPrice: '1200',
                              totalPrice: '4000',
                              taxInd: 'OTT01',
                              itemRefList: [
                                {
                                  itemRef: {
                                    id: 'PO_IntPosPlanFtthA100',
                                    parentId: 'PO_IntPosPlanFtthA100',
                                    serviceName: 'PO_IntPosPlanFtthA100',
                                  },
                                },
                              ],
                            },
                          },
                        ],
                        shippingRef: {
                          technology: 'MOV',
                          daneCodeCity: '73001000',
                          city: 'BOGOTA',
                          daneCodeProvince: '21',
                          province: 'CUNDINAMARCA',
                          villageCenterDaneCode: '21000100',
                          villageCenter: 'Suba',
                          neighborhood: 'Subachoque',
                          address: 'Calle 112 # 23-12',
                          region: 'Norte',
                          addressId: '21',
                          strata: '4',
                        },
                      },
                    },
                  ],
                },
              },
            ],
          },
        },
      },
    ],
    response: [{ idSolicitud: 'a' }],
    idCaseTcrm: '122',
  },
  {
    cmtRequestCrearSolicitud: [
      {
        customer: {
          isMigratedUser: false,
          user: 'hectorg',
          ip: '191.25.01.172',
          requestDate: '2008-09-28T20:49:45',
          customerInfo: {
            id: '1029818201',
            idType: 'CC',
            firstname: 'Ana',
            lastname: 'Fernandez Clower',
            mediumCharacteristic: {
              emailAddress: 'Lpinzon@gmail.com.co',
              phoneNumber: '3002323232',
              idCaseTcrm: 'ECOM-9362706851',
            },
            scId: '102910',
            transactionIdentity: '109219810',
            profileCustomerId: '109219810',
            agreementRef: {
              eBilling: 'S',
            },
            orderRefList: [
              {
                orderRef: {
                  id: '0',
                  date: '8/4/2020',
                  subOrderRefList: [
                    {
                      subOrderRef: {
                        id: '0',
                        salesProcess: 'HOG',
                        productType: 'Claro',
                        planType: 'POS',
                        salesType: 'ACT',
                        deliveryType: 'ID',
                        paymentMethodRef: {
                          id: 'CON',
                        },
                        accountRef: {
                          id: '102919201012',
                          type: 'M',
                        },
                        productRefList: [
                          {
                            productRef: {
                              planId: 'PO_IntPosPlanFtthA100',
                              planDescription: 'Internet 100 MB FTTH',
                              price: '6000',
                              nonTaxPrice: '1200',
                              totalPrice: '4000',
                              taxInd: 'OTT01',
                              itemRefList: [
                                {
                                  itemRef: {
                                    id: 'PO_IntPosPlanFtthA100',
                                    parentId: 'PO_IntPosPlanFtthA100',
                                    serviceName: 'PO_IntPosPlanFtthA100',
                                  },
                                },
                              ],
                            },
                          },
                        ],
                        shippingRef: {
                          technology: 'MOV',
                          daneCodeCity: '73001000',
                          city: 'BOGOTA',
                          daneCodeProvince: '21',
                          province: 'CUNDINAMARCA',
                          villageCenterDaneCode: '21000100',
                          villageCenter: 'Suba',
                          neighborhood: 'Subachoque',
                          address: 'Calle 112 # 23-12',
                          region: 'Norte',
                          addressId: '21',
                          strata: '4',
                        },
                      },
                    },
                  ],
                },
              },
            ],
          },
        },
      },
    ],
    response: [{ idSolicitud: 'a' }],
    idCaseTcrm: '122',
  },
  {
    cmtRequestCrearSolicitud: [
      {
        customer: {
          isMigratedUser: false,
          user: 'hectorg',
          ip: '191.25.01.172',
          requestDate: '2008-09-28T20:49:45',
          customerInfo: {
            id: '1029818201',
            idType: 'CC',
            firstname: 'Ana',
            lastname: 'Fernandez Clower',
            mediumCharacteristic: {
              emailAddress: 'Lpinzon@gmail.com.co',
              phoneNumber: '3002323232',
              idCaseTcrm: 'ECOM-9362706851',
            },
            scId: '102910',
            transactionIdentity: '109219810',
            profileCustomerId: '109219810',
            agreementRef: {
              eBilling: 'S',
            },
            orderRefList: [
              {
                orderRef: {
                  id: '0',
                  date: '8/4/2020',
                  subOrderRefList: [
                    {
                      subOrderRef: {
                        id: '0',
                        salesProcess: 'HOG',
                        productType: 'Claro',
                        planType: 'POS',
                        salesType: 'ACT',
                        deliveryType: 'ID',
                        paymentMethodRef: {
                          id: 'CON',
                        },
                        accountRef: {
                          id: '102919201012',
                          type: 'M',
                        },
                        productRefList: [
                          {
                            productRef: {
                              planId: 'PO_IntPosPlanFtthA100',
                              planDescription: 'Internet 100 MB FTTH',
                              price: '6000',
                              nonTaxPrice: '1200',
                              totalPrice: '4000',
                              taxInd: 'OTT01',
                              itemRefList: [
                                {
                                  itemRef: {
                                    id: 'PO_IntPosPlanFtthA100',
                                    parentId: 'PO_IntPosPlanFtthA100',
                                    serviceName: 'PO_IntPosPlanFtthA100',
                                  },
                                },
                              ],
                            },
                          },
                        ],
                        shippingRef: {
                          technology: 'MOV',
                          daneCodeCity: '73001000',
                          city: 'BOGOTA',
                          daneCodeProvince: '21',
                          province: 'CUNDINAMARCA',
                          villageCenterDaneCode: '21000100',
                          villageCenter: 'Suba',
                          neighborhood: 'Subachoque',
                          address: 'Calle 112 # 23-12',
                          region: 'Norte',
                          addressId: '21',
                          strata: '4',
                        },
                      },
                    },
                  ],
                },
              },
            ],
          },
        },
      },
    ],
    response: [{ idSolicitud: 'a' }],
    idCaseTcrm: '122',
  },
];

export const structureServiceReq: StructuresDTO = {
  geographicAddressList: [
    {
      geographicAddress: [
        {
          daneCode: '66682000',
          neighborhood: 'LOS BLOQUES',
          addressType: 'BM',
        },
      ],
      alternateGeographicAddress: [
        {
          nivel1Type: '',
          nivel2Type: '',
          nivel3Type: '',
          nivel4Type: '',
          nivel5Type: '',
          nivel6Type: '',
          nivel1Value: '',
          nivel2Value: '',
          nivel3Value: '',
          nivel4Value: '',
          nivel5Value: '',
          nivel6Value: '',
        },
      ],
      complements: [
        {
          nivel1Type: '',
          nivel1Value: '',
          nivel2Type: '',
          nivel3Type: '',
          nivel4Type: '',
          nivel6Type: '',
          nivel2Value: '',
          nivel3Value: '',
          nivel4Value: '',
          nivel6Value: '',
          nivel5Type: '',
          nivel5Value: '',
        },
      ],
      plateTypeIt: '',
      plateValueIt: '',
    },
  ],
};

export const structureUcResp = {
  '0': ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'A'],
  '1': ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'C'],
  '2': ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'E'],
  '3': ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'G'],
  '4': ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'I'],
  '5': ['OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'OTRO', 'MANZANA', 'K'],
};

export const altSegm = [
  {
    nivel4Type: 'MANZANA',
    nivel4Value: 'A,C,E,G,I,K',
  },
];
