export const requestDummy = {
  isMigratedUser: false,
  daneCity: '11001',
  salesProducts: [
    {
      procSales: 'TER',
      typeProduct: 'Claro',
      coverageId: 'CORBETA015',
      typePlan: 'POS',
      typeSales: 'ACT',
      products: [
        {
          partNumber: '7017324',
          quantity: 1,
        },
        {
          partNumber: '70024050',
          quantity: 1,
        },
      ],
    },
  ],
};

export const requestDummyInvalid = {};

export const requestDummyIncorrect = {
  isMigratedUser: false,
  daneCity: '101',
  salesProducts: [
    {
      procSales: 'TER',
      typeProduct: 'Claro',
      coverageId: 'CORBETA015',
      typePlan: 'POS',
      typeSales: 'ACT',
      products: [
        {
          partNumber: '7017324',
          quantity: 1,
        },
      ],
    },
  ],
};

export const requestDummyInspira = {
  isMigratedUser: true,
  daneCity: '11001',
  salesProducts: [
    {
      procSales: 'TER',
      typeProduct: 'Claro',
      coverageId: 'CORBETA015',
      typePlan: 'POS',
      typeSales: 'ACT',
      products: [
        {
          partNumber: '7017324',
          quantity: 1,
        },
        {
          partNumber: '70024050',
          quantity: 1,
        },
      ],
    },
  ],
};

export const requestDummyClaroShop = {
  isMigratedUser: false,
  daneCity: '10001',
  salesProducts: [
    {
      procSales: 'TEC',
      typeProduct: 'ClaroShop',
      typePlan: '',
      typeSales: '',
      coverageId: 'CORBETA121',
      products: [
        {
          partNumber: '7003730',
          quantity: 2,
        },
      ],
    },
  ],
};

export const requestHomepassUC = {
  geographicAddressList: {
    geographicAddress: [
      {
        type: 'CK',
        streetType: 'CALLE',
        streetNr: '75',
        streetSuffix: '',
        streetName: '',
        streetNrGenerator: '12',
        streetTypeGenerator: '',
        streetLtGenerator: '',
        streetBisGenerator: '',
        streetBlockGenerator: '',
        plate: '70',
        streetAlt: '',
        neighborhood: '',
        streetLt: '',
        streetNlPostViaP: '',
        streetBis: '',
        streetBlock: '',
        streetNlPostViaG: '',
        complements: {
          nivel1Type: '',
          nivel2Type: '',
          nivel3Type: '',
          nivel4Type: '',
          nivel5Type: 'CASA',
          nivel6Type: '',
          nivel1Value: '',
          nivel2Value: '',
          nivel3Value: '',
          nivel4Value: '',
          nivel5Value: '',
          nivel6Value: '',
        },
        alternateGeographicAddress: {
          nivel1Type: '',
          nivel2Type: '',
          nivel3Type: '',
          nivel4Type: '',
          nivel5Type: '',
          nivel6Type: '',
          nivel1Value: '',
          nivel2Value: '',
          nivel3Value: '',
          nivel4Value: '',
          nivel5Value: '',
          nivel6Value: '',
        },
        cadastreId: 'd2079',
        plateValueLt: '',
        plateTypeLt: '',
        geoState: 'D',
        idDetailAddress: '',
        word3G: '',
      },
    ],
  },
  transactionId: '123',
  ip: '127.0.0.1',
};

export const mockedResponseTabulada1 = {
  executed: true,
  status: 200,
  data: {
    type: 'cmtAddressGeneralResponseDto',
    message: 'Operacion Exitosa',
    messageType: 'I',
    idCentroPoblado: '24926',
    centroPoblado: 'BOGOTA',
    listAddresses: [
      {
        splitAddres: {
          idDireccionDetallada: '2079',
          dirPrincAlt: 'P',
          tipoViaPrincipal: 'CALLE',
          numViaPrincipal: '75',
          numViaGeneradora: '12',
          placaDireccion: '70',
          cpTipoNivel5: 'CASA',
          estadoDirGeo: 'D',
          direccionTexto: 'CL 75 12 70',
          direccionId: 2079,
        },
        dirAlterna: false,
      },
    ],
  },
  message: 'OK',
  requestInfo: {
    url: 'http://100.123.17.209:8100/CMatricesAs400Services-war/location/address/consultaDireccionExactaTabulada',
    method: 'put',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      requestStartedAt: 1683305687414,
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 1158,
      processingTime: 1463,
    },
    params: undefined,
    data: '{"headerRequest":{"transactionId":"18327983","system":"EC9_B2C","requestDate":"2023-05-05T16:54:41.666Z","ipApplication":"10.2.192.2"},"codigoDane":"11001000","direccion":"CL 75 12 70","isDth":"true","nodoGestion":"node","user":"user258","estrato":"1","direccionTabulada":{"idTipoDireccion":"CK","dirPrincAlt":"","barrio":"","tipoViaPrincipal":"CALLE","numViaPrincipal":"75","ltViaPrincipal":"","nlPostViaP":"","bisViaPrincipal":"","cuadViaPrincipal":"","tipoViaGeneradora":"","numViaGeneradora":"12","ltViaGeneradora":"","nlPostViaG":"","bisViaGeneradora":"","cuadViaGeneradora":"","placaDireccion":"70","cpTipoNivel1":"","cpTipoNivel2":"","cpTipoNivel3":"","cpTipoNivel4":"","cpTipoNivel5":"CASA","cpTipoNivel6":"","cpValorNivel1":"","cpValorNivel2":"","cpValorNivel3":"","cpValorNivel4":"","cpValorNivel5":"","cpValorNivel6":"","mzTipoNivel1":"","mzTipoNivel2":"","mzTipoNivel3":"","mzTipoNivel4":"","mzTipoNivel5":"","mzValorNivel1":"","mzValorNivel2":"","mzValorNivel3":"","mzValorNivel4":"","mzValorNivel5":"","idDirCatastro":"d2079","mzTipoNivel6":"","mzValorNivel6":"","itTipoPlaca":"","itValorPlaca":"","estadoDirGeo":"D","idDireccionDetallada":""}}',
    timeout: 15000,
    source: '/CMatricesAs400Services-war/location/address/consultaDireccionExactaTabulada',
  },
};
export const mockedResponseGeneral1 = {
  executed: true,
  status: 200,
  data: {
    message: 'Operacion Exitosa',
    messageType: 'I',
    addresses: {
      addressId: '2079',
      city: {
        cityId: 24926,
        name: 'BOGOTA',
        daneCode: '11001000',
        uperGeographycLevel: {
          geographyStateId: 122,
          name: 'BOGOTÁ D.C.',
          daneCode: '11001',
          geographycLevelType: 'CIUDAD',
          uperGeographycLevel: {
            geographyStateId: 7,
            name: 'BOGOTA',
            daneCode: '11',
            geographycLevelType: 'DEPARTAMENTO',
            uperGeographycLevel: null,
          },
        },
        region: {
          regionId: 3161,
          name: 'REGIONAL TECNICA CENTRAL COLOMBIA',
          technicalCode: 'RTW1',
        },
        claroCode: 'BOG',
        geographycLevelType: 'CENTRO POBLADO',
      },
      igacAddress: 'CL 75 12 70',
      adressReliability: 99,
      latitudeCoordinate: '4,66131837',
      lengthCoordinate: '-74,05870882',
      splitAddres: {
        idTipoDireccion: 'CK',
        dirPrincAlt: 'P',
        barrio: null,
        tipoViaPrincipal: 'CALLE',
        numViaPrincipal: '75',
        ltViaPrincipal: null,
        nlPostViaP: null,
        bisViaPrincipal: null,
        cuadViaPrincipal: null,
        tipoViaGeneradora: null,
        numViaGeneradora: '12',
        ltViaGeneradora: null,
        nlPostViaG: null,
        bisViaGeneradora: null,
        cuadViaGeneradora: null,
        placaDireccion: '70',
        cpTipoNivel1: null,
        cpTipoNivel2: null,
        cpTipoNivel3: null,
        cpTipoNivel4: null,
        cpTipoNivel5: 'CASA',
        cpTipoNivel6: null,
        cpValorNivel1: null,
        cpValorNivel2: null,
        cpValorNivel3: null,
        cpValorNivel4: null,
        cpValorNivel5: null,
        cpValorNivel6: null,
        mzTipoNivel1: null,
        mzTipoNivel2: null,
        mzTipoNivel3: null,
        mzTipoNivel4: null,
        mzTipoNivel5: null,
        mzValorNivel1: null,
        mzValorNivel2: null,
        mzValorNivel3: null,
        mzValorNivel4: null,
        mzValorNivel5: null,
        idDirCatastro: 'd2079',
        mzTipoNivel6: null,
        mzValorNivel6: null,
        itTipoPlaca: null,
        itValorPlaca: null,
        estadoDirGeo: 'D',
        letra3G: null,
      },
      listCover: [
        {
          technology: 'BI',
          node: '3B4023',
          state: 'ACT',
          qualificationDate: '2018/12/04',
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
        {
          technology: 'FOG',
          node: 'G06HXG',
          state: 'ACT',
          qualificationDate: '7000/01/01',
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
        {
          technology: 'DTH',
          node: 'HCHICB',
          state: 'ACT',
          qualificationDate: '2018/12/04',
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
        {
          technology: 'LTE',
          node: 'Viable',
          state: null,
          qualificationDate: null,
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
        {
          technology: 'FOU',
          node: 'U06HXG',
          state: 'ACT',
          qualificationDate: '7000/01/01',
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
      ],
      listCarrierCover: ['(LOGYTECH)(1)', '(LOGYTECH)(3)'],
      stratum: '1',
      mensajeDireccionAntigua: null,
      listHhpps: [
        {
          hhppId: 2079,
          state: 'CS',
          technology: 'BI',
          viability: {
            resultadoValidacion: false,
            mensajes: null,
            codRespuesta: 'I',
            mensajeRespuesta: 'Na hay proyecto para procesar',
            nombreProyecto: null,
          },
          node: {
            codeNode: '3B4023',
            state: 'ACT',
            qualificationDate: '2018/12/04',
            nodeName: 'UNIVERSIDAD 6                ',
            technology: 'BI',
          },
          subCcmmTechnology: null,
          listAddresMarks: [
            {
              markId: 'ESO',
              descriptionMark: 'CAMBIO ESTRATO POR SOLICITUD',
            },
          ],
          constructionType: 'APARTAMENTO',
          rushtype: 'CAJA RELIANCE',
          notasHhpp: null,
          accountNumber: '14301964',
        },
      ],
    },
  },
  message: 'OK',
  requestInfo: {
    url: 'http://100.123.17.209:8100/CMatricesAs400Services-war/location/address/consultaDireccion',
    method: 'put',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      requestStartedAt: 1683305839980,
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 158,
      processingTime: 1747,
    },
    params: undefined,
    data: '{"headerRequest":{"transactionId":"18327983","system":"Ecommerce","requestDate":"2023-05-05T16:56:44.487Z","ipApplication":"10.2.192.2"},"idDireccion":"2079"}',
    timeout: 15000,
    source: '/CMatricesAs400Services-war/location/address/consultaDireccion',
  },
};

export const requestHomepassUC2 = {
  geographicAddressList: {
    geographicAddress: [
      {
        type: 'CK',
        streetType: 'CARRERA',
        streetNr: '2',
        streetSuffix: '',
        streetName: 'ESTE',
        streetNrGenerator: '70',
        streetTypeGenerator: '',
        streetLtGenerator: 'A',
        streetBisGenerator: '',
        streetBlockGenerator: '',
        plate: '86',
        streetAlt: '',
        neighborhood: 'LAS ACACIAS',
        streetLt: '',
        streetNlPostViaP: '',
        streetBis: '',
        streetBlock: '',
        streetNlPostViaG: '',
        complements: {
          nivel1Type: '',
          nivel2Type: '',
          nivel3Type: '',
          nivel4Type: '',
          nivel5Type: 'APARTAMENTO',
          nivel6Type: '',
          nivel1Value: '',
          nivel2Value: '',
          nivel3Value: '',
          nivel4Value: '',
          nivel5Value: '501',
          nivel6Value: '',
        },
        alternateGeographicAddress: {
          nivel1Type: '',
          nivel2Type: '',
          nivel3Type: '',
          nivel4Type: '',
          nivel5Type: '',
          nivel6Type: '',
          nivel1Value: '',
          nivel2Value: '',
          nivel3Value: '',
          nivel4Value: '',
          nivel5Value: '',
          nivel6Value: '',
        },
        cadastreId: 's3240083',
        plateValueLt: '',
        plateTypeLt: '',
        geoState: 'Y',
        idDetailAddress: '',
        word3G: '',
      },
    ],
  },
};

export const mockedResponseTabulada2 = {
  executed: true,
  status: 200,
  data: {
    type: 'cmtAddressGeneralResponseDto',
    message: 'No se encontro ninguna dirección con los criterios de busqueda ingresados',
    messageType: 'I',
    idCentroPoblado: '24926',
    centroPoblado: 'BOGOTA',
    listAddresses: [],
  },
  message: 'OK',
  requestInfo: {
    url: 'http://100.123.17.209:8100/CMatricesAs400Services-war/location/address/consultaDireccionExactaTabulada',
    method: 'put',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      requestStartedAt: 1683308570788,
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 1198,
      processingTime: 268,
    },
    params: undefined,
    data: '{"headerRequest":{"transactionId":"18327983","system":"EC9_B2C","requestDate":"2023-05-05T17:42:43.221Z","ipApplication":"10.2.192.2"},"codigoDane":"11001000","direccion":"KR 2 ESTE 70 A 86  AP 501","isDth":"true","nodoGestion":"node","user":"user258","estrato":"1","direccionTabulada":{"idTipoDireccion":"CK","dirPrincAlt":"","barrio":"LAS ACACIAS","tipoViaPrincipal":"CARRERA","numViaPrincipal":"2","ltViaPrincipal":"","nlPostViaP":"","bisViaPrincipal":"","cuadViaPrincipal":"","tipoViaGeneradora":"","numViaGeneradora":"70","ltViaGeneradora":"A","nlPostViaG":"","bisViaGeneradora":"","cuadViaGeneradora":"","placaDireccion":"86","cpTipoNivel1":"","cpTipoNivel2":"","cpTipoNivel3":"","cpTipoNivel4":"","cpTipoNivel5":"APARTAMENTO","cpTipoNivel6":"","cpValorNivel1":"","cpValorNivel2":"","cpValorNivel3":"","cpValorNivel4":"","cpValorNivel5":"501","cpValorNivel6":"","mzTipoNivel1":"","mzTipoNivel2":"","mzTipoNivel3":"","mzTipoNivel4":"","mzTipoNivel5":"","mzValorNivel1":"","mzValorNivel2":"","mzValorNivel3":"","mzValorNivel4":"","mzValorNivel5":"","idDirCatastro":"s3240083","mzTipoNivel6":"","mzValorNivel6":"","itTipoPlaca":"","itValorPlaca":"","estadoDirGeo":"Y","idDireccionDetallada":""}}',
    timeout: 15000,
    source: '/CMatricesAs400Services-war/location/address/consultaDireccionExactaTabulada',
  },
};

export const mockedResponseGeneral2 = {
  executed: true,
  status: 200,
  data: {
    type: 'cmtAddressGeneralResponseDto',
    message: 'Operacion Exitosa',
    messageType: 'I',
    idCentroPoblado: '24926',
    centroPoblado: 'BOGOTA',
    listAddresses: [
      {
        splitAddres: {
          idDireccionDetallada: '7719115',
          dirPrincAlt: 'P',
          barrio: 'BOSQUE CALDERON TEJADA',
          tipoViaPrincipal: 'CARRERA',
          numViaPrincipal: '2',
          cuadViaPrincipal: 'ESTE',
          numViaGeneradora: '70',
          ltViaGeneradora: 'A',
          placaDireccion: '86',
          cpTipoNivel5: 'APARTAMENTO',
          cpValorNivel5: '501',
          direccionTexto: 'KR 2 ESTE 70 A 86 AP 501',
          direccionId: 3722370,
          subdireccionId: 3240083,
        },
        dirAlterna: false,
      },
      {
        splitAddres: {
          idDireccionDetallada: '7719114',
          dirPrincAlt: 'P',
          barrio: 'BOSQUE CALDERON TEJADA',
          tipoViaPrincipal: 'CARRERA',
          numViaPrincipal: '2',
          cuadViaPrincipal: 'ESTE',
          numViaGeneradora: '70',
          ltViaGeneradora: 'A',
          placaDireccion: '86',
          cpTipoNivel5: 'APARTAMENTO',
          cpValorNivel5: '401',
          direccionTexto: 'KR 2 ESTE 70 A 86 AP 401',
          direccionId: 3722370,
          subdireccionId: 3240082,
        },
        dirAlterna: false,
      },
      {
        splitAddres: {
          idDireccionDetallada: '7719113',
          dirPrincAlt: 'P',
          barrio: 'BOSQUE CALDERON TEJADA',
          tipoViaPrincipal: 'CARRERA',
          numViaPrincipal: '2',
          cuadViaPrincipal: 'ESTE',
          numViaGeneradora: '70',
          ltViaGeneradora: 'A',
          placaDireccion: '86',
          cpTipoNivel5: 'APARTAMENTO',
          cpValorNivel5: '301',
          direccionTexto: 'KR 2 ESTE 70 A 86 AP 301',
          direccionId: 3722370,
          subdireccionId: 3240081,
        },
        dirAlterna: false,
      },
      {
        splitAddres: {
          idDireccionDetallada: '7719112',
          dirPrincAlt: 'P',
          barrio: 'BOSQUE CALDERON TEJADA',
          tipoViaPrincipal: 'CARRERA',
          numViaPrincipal: '2',
          cuadViaPrincipal: 'ESTE',
          numViaGeneradora: '70',
          ltViaGeneradora: 'A',
          placaDireccion: '86',
          cpTipoNivel5: 'APARTAMENTO',
          cpValorNivel5: '201',
          direccionTexto: 'KR 2 ESTE 70 A 86 AP 201',
          direccionId: 3722370,
          subdireccionId: 3240080,
        },
        dirAlterna: false,
      },
      {
        splitAddres: {
          idDireccionDetallada: '7719111',
          dirPrincAlt: 'P',
          barrio: 'BOSQUE CALDERON TEJADA',
          tipoViaPrincipal: 'CARRERA',
          numViaPrincipal: '2',
          cuadViaPrincipal: 'ESTE',
          numViaGeneradora: '70',
          ltViaGeneradora: 'A',
          placaDireccion: '86',
          cpTipoNivel5: 'APARTAMENTO',
          cpValorNivel5: '101',
          direccionTexto: 'KR 2 ESTE 70 A 86 AP 101',
          direccionId: 3722370,
          subdireccionId: 3240079,
        },
        dirAlterna: false,
      },
      {
        splitAddres: {
          idDireccionDetallada: '6006891',
          dirPrincAlt: 'P',
          barrio: 'BOSQUE CALDERON TEJADA',
          tipoViaPrincipal: 'CARRERA',
          numViaPrincipal: '2',
          cuadViaPrincipal: 'ESTE',
          numViaGeneradora: '70',
          ltViaGeneradora: 'A',
          placaDireccion: '86',
          cpTipoNivel5: 'CASA',
          direccionTexto: 'KR 2 ESTE 70 A 86',
          direccionId: 3722370,
        },
        dirAlterna: false,
      },
    ],
  },
  message: 'OK',
  requestInfo: {
    url: 'http://100.123.17.209:8100/CMatricesAs400Services-war/location/address/consultaDireccionGeneral',
    method: 'put',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      requestStartedAt: 1683308668477,
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 1198,
      processingTime: 3693,
    },
    params: undefined,
    data: '{"headerRequest":{"transactionId":"18327983","system":"EC9_B2C","requestDate":"2023-05-05T17:42:43.221Z","ipApplication":"10.2.192.2"},"codigoDane":"11001000","direccion":"KR 2 ESTE 70 A 86  AP 501","isDth":"true","nodoGestion":"node","user":"user258","estrato":"1","direccionTabulada":{"idTipoDireccion":"CK","dirPrincAlt":"","barrio":"LAS ACACIAS","tipoViaPrincipal":"CARRERA","numViaPrincipal":"2","ltViaPrincipal":"","nlPostViaP":"","bisViaPrincipal":"","cuadViaPrincipal":"","tipoViaGeneradora":"","numViaGeneradora":"70","ltViaGeneradora":"A","nlPostViaG":"","bisViaGeneradora":"","cuadViaGeneradora":"","placaDireccion":"86","cpTipoNivel1":"","cpTipoNivel2":"","cpTipoNivel3":"","cpTipoNivel4":"","cpTipoNivel5":"APARTAMENTO","cpTipoNivel6":"","cpValorNivel1":"","cpValorNivel2":"","cpValorNivel3":"","cpValorNivel4":"","cpValorNivel5":"501","cpValorNivel6":"","mzTipoNivel1":"","mzTipoNivel2":"","mzTipoNivel3":"","mzTipoNivel4":"","mzTipoNivel5":"","mzValorNivel1":"","mzValorNivel2":"","mzValorNivel3":"","mzValorNivel4":"","mzValorNivel5":"","idDirCatastro":"s3240083","mzTipoNivel6":"","mzValorNivel6":"","itTipoPlaca":"","itValorPlaca":"","estadoDirGeo":"Y","idDireccionDetallada":""}}',
    timeout: 15000,
    source: '/CMatricesAs400Services-war/location/address/consultaDireccionGeneral',
  },
};

export const mockedResponseCrearDB = [
  {
    $__: {
      strictMode: true,
      selected: undefined,
      shardval: undefined,
      saveError: undefined,
      validationError: undefined,
      adhocPaths: undefined,
      removing: undefined,
      inserting: undefined,
      saving: undefined,
      version: undefined,
      getters: {},
      _id: {
        _bsontype: 'ObjectID',
        id: new Uint8Array([100, 85, 64, 249, 158, 75, 99, 102, 52, 71, 177, 132]),
      },
      populate: undefined,
      populated: undefined,
      wasPopulated: false,
      scope: undefined,
      activePaths: {
        paths: {},
        states: {
          ignore: {},
          default: {},
          init: {},
          modify: {},
          require: {},
        },
        stateNames: ['require', 'modify', 'init', 'default', 'ignore'],
      },
      session: null,
      $setCalled: {},
      ownerDocument: undefined,
      fullPath: undefined,
      emitter: {
        _events: {},
        _eventsCount: 0,
        _maxListeners: 0,
      },
      $options: {
        defaults: true,
      },
      validating: null,
      backup: {
        activePaths: {
          modify: {
            user: true,
            sourceAplication: true,
            destinationAplication: true,
            daneCode: true,
            idCaseTcrm: true,
            cmtRequestCrearSolicitud: true,
            idAddress: true,
            address: true,
            response: true,
            stateHHPP: true,
            stateTransaction: true,
            createdAt: true,
            updateAt: true,
            isMigratedUser: true,
          },
          default: {
            _id: true,
          },
        },
        validationError: undefined,
        errors: undefined,
      },
    },
    isNew: false,
    errors: undefined,
    $locals: {},
    $op: null,
    _doc: {
      response: [],
      address: [
        {
          isMigratedUser: false,
          transactionId: '18327983',
          ip: '10.2.192.2',
          daneCode: '11001000',
          address: 'KR 2 ESTE 70 A 86  AP 501',
          isDth: 'true',
          managementNode: 'node',
          user: 'user258',
          strata: '1',
          geographicAddressList: {
            geographicAddress: [
              {
                type: 'CK',
                streetType: 'CARRERA',
                streetNr: '2',
                streetSuffix: '',
                streetName: 'ESTE',
                streetNrGenerator: '70',
                streetTypeGenerator: '',
                streetLtGenerator: 'A',
                streetBisGenerator: '',
                streetBlockGenerator: '',
                plate: '86',
                streetAlt: '',
                neighborhood: 'LAS ACACIAS',
                streetLt: '',
                streetNlPostViaP: '',
                streetBis: '',
                streetBlock: '',
                streetNlPostViaG: '',
                complements: {
                  nivel1Type: '',
                  nivel2Type: '',
                  nivel3Type: '',
                  nivel4Type: '',
                  nivel5Type: 'APARTAMENTO',
                  nivel6Type: '',
                  nivel1Value: '',
                  nivel2Value: '',
                  nivel3Value: '',
                  nivel4Value: '',
                  nivel5Value: '501',
                  nivel6Value: '',
                },
                alternateGeographicAddress: {
                  nivel1Type: '',
                  nivel2Type: '',
                  nivel3Type: '',
                  nivel4Type: '',
                  nivel5Type: '',
                  nivel6Type: '',
                  nivel1Value: '',
                  nivel2Value: '',
                  nivel3Value: '',
                  nivel4Value: '',
                  nivel5Value: '',
                  nivel6Value: '',
                },
                cadastreId: 's3240083',
                plateValueLt: '',
                plateTypeLt: '',
                geoState: 'Y',
                idDetailAddress: '',
                word3G: '',
              },
            ],
          },
        },
      ],
      cmtRequestCrearSolicitud: [],
      _id: {
        _bsontype: 'ObjectID',
        id: new Uint8Array([100, 85, 64, 249, 158, 75, 99, 102, 52, 71, 177, 132]),
      },
      user: 'user258',
      sourceAplication: 'ECOM',
      destinationAplication: 'MGL',
      daneCode: '11001000',
      idCaseTcrm: 'ECOM-4565208744',
      idAddress: '3722370',
      stateHHPP: 'HHPP NO EXISTE',
      stateTransaction: 'INICIADO',
      createdAt: '2023-05-05T17:46:33.618Z',
      updateAt: '2023-05-05T17:46:33.618Z',
      isMigratedUser: false,
    },
  },
];

export const mockedResponseGeneral3 = {
  executed: true,
  status: 200,
  data: {
    message: 'Operacion Exitosa',
    messageType: 'I',
    addresses: {
      addressId: '2079',
      city: {
        cityId: 24926,
        name: 'BOGOTA',
        daneCode: '11001000',
        uperGeographycLevel: {
          geographyStateId: 122,
          name: 'BOGOTÁ D.C.',
          daneCode: '11001',
          geographycLevelType: 'CIUDAD',
          uperGeographycLevel: {
            geographyStateId: 7,
            name: 'BOGOTA',
            daneCode: '11',
            geographycLevelType: 'DEPARTAMENTO',
            uperGeographycLevel: null,
          },
        },
        region: {
          regionId: 3161,
          name: 'REGIONAL TECNICA CENTRAL COLOMBIA',
          technicalCode: 'RTW1',
        },
        claroCode: 'BOG',
        geographycLevelType: 'CENTRO POBLADO',
      },
      igacAddress: 'CL 75 12 70',
      adressReliability: 99,
      latitudeCoordinate: '4,66131837',
      lengthCoordinate: '-74,05870882',
      splitAddres: {
        idTipoDireccion: 'CK',
        dirPrincAlt: 'P',
        barrio: null,
        tipoViaPrincipal: 'CALLE',
        numViaPrincipal: '75',
        ltViaPrincipal: null,
        nlPostViaP: null,
        bisViaPrincipal: null,
        cuadViaPrincipal: null,
        tipoViaGeneradora: null,
        numViaGeneradora: '12',
        ltViaGeneradora: null,
        nlPostViaG: null,
        bisViaGeneradora: null,
        cuadViaGeneradora: null,
        placaDireccion: '70',
        cpTipoNivel1: null,
        cpTipoNivel2: null,
        cpTipoNivel3: null,
        cpTipoNivel4: null,
        cpTipoNivel5: 'CASA',
        cpTipoNivel6: null,
        cpValorNivel1: null,
        cpValorNivel2: null,
        cpValorNivel3: null,
        cpValorNivel4: null,
        cpValorNivel5: null,
        cpValorNivel6: null,
        mzTipoNivel1: null,
        mzTipoNivel2: null,
        mzTipoNivel3: null,
        mzTipoNivel4: null,
        mzTipoNivel5: null,
        mzValorNivel1: null,
        mzValorNivel2: null,
        mzValorNivel3: null,
        mzValorNivel4: null,
        mzValorNivel5: null,
        idDirCatastro: 'd2079',
        mzTipoNivel6: null,
        mzValorNivel6: null,
        itTipoPlaca: null,
        itValorPlaca: null,
        estadoDirGeo: 'D',
        letra3G: null,
      },
      listCover: [
        {
          technology: 'BI',
          node: '3B4023',
          state: 'ACT',
          qualificationDate: '2018/12/04',
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
        {
          technology: 'FOG',
          node: 'G06HXG',
          state: 'ACT',
          qualificationDate: '7000/01/01',
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
        {
          technology: 'DTH',
          node: 'HCHICB',
          state: 'ACT',
          qualificationDate: '2018/12/04',
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
        {
          technology: 'LTE',
          node: 'Viable',
          state: null,
          qualificationDate: null,
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
        {
          technology: 'FOU',
          node: 'U06HXG',
          state: 'ACT',
          qualificationDate: '7000/01/01',
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
      ],
      listCarrierCover: ['(LOGYTECH)(1)', '(LOGYTECH)(3)'],
      stratum: '1',
      mensajeDireccionAntigua: null,
      listHhpps: undefined,
    },
  },
  message: 'OK',
  requestInfo: {
    url: 'http://100.123.17.209:8100/CMatricesAs400Services-war/location/address/consultaDireccion',
    method: 'put',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      requestStartedAt: 1683305839980,
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 158,
      processingTime: 1747,
    },
    params: undefined,
    data: '{"headerRequest":{"transactionId":"18327983","system":"Ecommerce","requestDate":"2023-05-05T16:56:44.487Z","ipApplication":"10.2.192.2"},"idDireccion":"2079"}',
    timeout: 15000,
    source: '/CMatricesAs400Services-war/location/address/consultaDireccion',
  },
};

export const mockedResponseGeneral4 = {
  executed: true,
  status: 200,
  data: {
    message: 'Operacion Exitosa',
    messageType: 'E',
    addresses: {
      addressId: '2079',
      city: {
        cityId: 24926,
        name: 'BOGOTA',
        daneCode: '11001000',
        uperGeographycLevel: {
          geographyStateId: 122,
          name: 'BOGOTÁ D.C.',
          daneCode: '11001',
          geographycLevelType: 'CIUDAD',
          uperGeographycLevel: {
            geographyStateId: 7,
            name: 'BOGOTA',
            daneCode: '11',
            geographycLevelType: 'DEPARTAMENTO',
            uperGeographycLevel: null,
          },
        },
        region: {
          regionId: 3161,
          name: 'REGIONAL TECNICA CENTRAL COLOMBIA',
          technicalCode: 'RTW1',
        },
        claroCode: 'BOG',
        geographycLevelType: 'CENTRO POBLADO',
      },
      igacAddress: 'CL 75 12 70',
      adressReliability: 99,
      latitudeCoordinate: '4,66131837',
      lengthCoordinate: '-74,05870882',
      splitAddres: {
        idTipoDireccion: 'CK',
        dirPrincAlt: 'P',
        barrio: null,
        tipoViaPrincipal: 'CALLE',
        numViaPrincipal: '75',
        ltViaPrincipal: null,
        nlPostViaP: null,
        bisViaPrincipal: null,
        cuadViaPrincipal: null,
        tipoViaGeneradora: null,
        numViaGeneradora: '12',
        ltViaGeneradora: null,
        nlPostViaG: null,
        bisViaGeneradora: null,
        cuadViaGeneradora: null,
        placaDireccion: '70',
        cpTipoNivel1: null,
        cpTipoNivel2: null,
        cpTipoNivel3: null,
        cpTipoNivel4: null,
        cpTipoNivel5: 'CASA',
        cpTipoNivel6: null,
        cpValorNivel1: null,
        cpValorNivel2: null,
        cpValorNivel3: null,
        cpValorNivel4: null,
        cpValorNivel5: null,
        cpValorNivel6: null,
        mzTipoNivel1: null,
        mzTipoNivel2: null,
        mzTipoNivel3: null,
        mzTipoNivel4: null,
        mzTipoNivel5: null,
        mzValorNivel1: null,
        mzValorNivel2: null,
        mzValorNivel3: null,
        mzValorNivel4: null,
        mzValorNivel5: null,
        idDirCatastro: 'd2079',
        mzTipoNivel6: null,
        mzValorNivel6: null,
        itTipoPlaca: null,
        itValorPlaca: null,
        estadoDirGeo: 'D',
        letra3G: null,
      },
      listCover: [
        {
          technology: 'BI',
          node: '3B4023',
          state: 'ACT',
          qualificationDate: '2018/12/04',
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
        {
          technology: 'FOG',
          node: 'G06HXG',
          state: 'ACT',
          qualificationDate: '7000/01/01',
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
        {
          technology: 'DTH',
          node: 'HCHICB',
          state: 'ACT',
          qualificationDate: '2018/12/04',
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
        {
          technology: 'LTE',
          node: 'Viable',
          state: null,
          qualificationDate: null,
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
        {
          technology: 'FOU',
          node: 'U06HXG',
          state: 'ACT',
          qualificationDate: '7000/01/01',
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
      ],
      listCarrierCover: ['(LOGYTECH)(1)', '(LOGYTECH)(3)'],
      stratum: '0',
      mensajeDireccionAntigua: null,
      listHhpps: undefined,
    },
  },
  message: 'OK',
  requestInfo: {
    url: 'http://100.123.17.209:8100/CMatricesAs400Services-war/location/address/consultaDireccion',
    method: 'put',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      requestStartedAt: 1683305839980,
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 158,
      processingTime: 1747,
    },
    params: undefined,
    data: '{"headerRequest":{"transactionId":"18327983","system":"Ecommerce","requestDate":"2023-05-05T16:56:44.487Z","ipApplication":"10.2.192.2"},"idDireccion":"2079"}',
    timeout: 15000,
    source: '/CMatricesAs400Services-war/location/address/consultaDireccion',
  },
};

export const mockedResponseGeneral5 = {
  executed: true,
  status: 200,
  data: {
    message: 'Operacion Exitosa',
    messageType: 'I',
    addresses: {
      addressId: '2079',
      city: {
        cityId: 24926,
        name: 'BOGOTA',
        daneCode: '11001000',
        uperGeographycLevel: {
          geographyStateId: 122,
          name: 'BOGOTÁ D.C.',
          daneCode: '11001',
          geographycLevelType: 'CIUDAD',
          uperGeographycLevel: {
            geographyStateId: 7,
            name: 'BOGOTA',
            daneCode: '11',
            geographycLevelType: 'DEPARTAMENTO',
            uperGeographycLevel: null,
          },
        },
        region: {
          regionId: 3161,
          name: 'REGIONAL TECNICA CENTRAL COLOMBIA',
          technicalCode: 'RTW1',
        },
        claroCode: 'BOG',
        geographycLevelType: 'CENTRO POBLADO',
      },
      igacAddress: 'CL 75 12 70',
      adressReliability: 99,
      latitudeCoordinate: '4,66131837',
      lengthCoordinate: '-74,05870882',
      splitAddres: {
        idTipoDireccion: 'CK',
        dirPrincAlt: 'P',
        barrio: null,
        tipoViaPrincipal: 'CALLE',
        numViaPrincipal: '75',
        ltViaPrincipal: null,
        nlPostViaP: null,
        bisViaPrincipal: null,
        cuadViaPrincipal: null,
        tipoViaGeneradora: null,
        numViaGeneradora: '12',
        ltViaGeneradora: null,
        nlPostViaG: null,
        bisViaGeneradora: null,
        cuadViaGeneradora: null,
        placaDireccion: '70',
        cpTipoNivel1: null,
        cpTipoNivel2: null,
        cpTipoNivel3: null,
        cpTipoNivel4: null,
        cpTipoNivel5: 'CASA',
        cpTipoNivel6: null,
        cpValorNivel1: null,
        cpValorNivel2: null,
        cpValorNivel3: null,
        cpValorNivel4: null,
        cpValorNivel5: null,
        cpValorNivel6: null,
        mzTipoNivel1: null,
        mzTipoNivel2: null,
        mzTipoNivel3: null,
        mzTipoNivel4: null,
        mzTipoNivel5: null,
        mzValorNivel1: null,
        mzValorNivel2: null,
        mzValorNivel3: null,
        mzValorNivel4: null,
        mzValorNivel5: null,
        idDirCatastro: 'd2079',
        mzTipoNivel6: null,
        mzValorNivel6: null,
        itTipoPlaca: null,
        itValorPlaca: null,
        estadoDirGeo: 'D',
        letra3G: null,
      },
      listCover: [
        {
          technology: 'BI',
          node: '3B4023',
          state: 'ACT',
          qualificationDate: '2018/12/04',
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
        {
          technology: 'FOG',
          node: 'G06HXG',
          state: 'ACT',
          qualificationDate: '7000/01/01',
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
        {
          technology: 'DTH',
          node: 'HCHICB',
          state: 'ACT',
          qualificationDate: '2018/12/04',
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
        {
          technology: 'LTE',
          node: 'Viable',
          state: null,
          qualificationDate: null,
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
        {
          technology: 'FOU',
          node: 'U06HXG',
          state: 'ACT',
          qualificationDate: '7000/01/01',
          hhppExistente: false,
          isChecked: false,
          poligono: null,
          hhppMgl: null,
          colorTecno: null,
          isCobertura: false,
          tecnologiaSubMgl: null,
          validaCobertura: false,
          zona3G4G5G: false,
          nodoSitiData: null,
          stateName: null,
        },
      ],
      listCarrierCover: ['(LOGYTECH)(1)', '(LOGYTECH)(3)'],
      stratum: '0',
      mensajeDireccionAntigua: null,
      listHhpps: [
        {
          hhppId: 2079,
          state: 'CS',
          technology: 'BI',
          viability: {
            resultadoValidacion: false,
            mensajes: null,
            codRespuesta: 'I',
            mensajeRespuesta: 'Na hay proyecto para procesar',
            nombreProyecto: null,
          },
          node: {
            codeNode: '3B4023',
            state: 'ACT',
            qualificationDate: '2018/12/04',
            nodeName: 'UNIVERSIDAD 6                ',
            technology: 'BI',
          },
          subCcmmTechnology: null,
          listAddresMarks: [
            {
              markId: 'ESO',
              descriptionMark: 'CAMBIO ESTRATO POR SOLICITUD',
            },
          ],
          constructionType: 'APARTAMENTO',
          rushtype: 'CAJA RELIANCE',
          notasHhpp: null,
          accountNumber: '14301964',
        },
      ],
    },
  },
  message: 'OK',
  requestInfo: {
    url: 'http://100.123.17.209:8100/CMatricesAs400Services-war/location/address/consultaDireccion',
    method: 'put',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      requestStartedAt: 1683305839980,
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 158,
      processingTime: 1747,
    },
    params: undefined,
    data: '{"headerRequest":{"transactionId":"18327983","system":"Ecommerce","requestDate":"2023-05-05T16:56:44.487Z","ipApplication":"10.2.192.2"},"idDireccion":"2079"}',
    timeout: 15000,
    source: '/CMatricesAs400Services-war/location/address/consultaDireccion',
  },
};

export const requestHomepassUC3 = {
  geographicAddressList: {
    geographicAddress: [
      {
        type: 'CK',
        streetType: 'CALLE',
        streetNr: '75',
        streetSuffix: '',
        streetName: '',
        streetNrGenerator: '12',
        streetTypeGenerator: '',
        streetLtGenerator: '',
        streetBisGenerator: '',
        streetBlockGenerator: '',
        plate: '70',
        streetAlt: '',
        neighborhood: '',
        streetLt: '',
        streetNlPostViaP: '',
        streetBis: '',
        streetBlock: '',
        streetNlPostViaG: '',
        complements: {
          nivel1Type: '',
          nivel2Type: '',
          nivel3Type: '',
          nivel4Type: '',
          nivel5Type: 'CASA',
          nivel6Type: '',
          nivel1Value: '',
          nivel2Value: '',
          nivel3Value: '',
          nivel4Value: '',
          nivel5Value: '',
          nivel6Value: '',
        },
        alternateGeographicAddress: {
          nivel1Type: '',
          nivel2Type: '',
          nivel3Type: '',
          nivel4Type: '',
          nivel5Type: '',
          nivel6Type: '',
          nivel1Value: '',
          nivel2Value: '',
          nivel3Value: '',
          nivel4Value: '',
          nivel5Value: '',
          nivel6Value: '',
        },
        cadastreId: 'd2079',
        plateValueLt: '',
        plateTypeLt: '',
        geoState: 'D',
        idDetailAddress: '2222',
        word3G: '',
      },
    ],
  },
  transactionId: '123',
  ip: '127.0.0.1',
};
