export interface IMappingEquiment {
    PriceListUniqueId: string,    
    PriceListName: string,    
    CatentryPartNumber: string,    
    CatentyUniqueId: string,    
    Identifier: string,    
    Precedence: string,    
    StartDate: string,    
    EndDate: string,    
    LastUpdate: string,    
    QuantityUnitIdentifier: string,    
    MinimumQuantity: string,    
    Description: string,    
    PriceInCOP: string,    
    PriceInCOPTax: string,    
    PlazosSinImpuestos: string,    
    PlazosConImpuestos: string,    
    Field1: string,    
    Field2: string,    
    Delete: string
  }