version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=database
      - DB_PORT=1521
      - DB_USERNAME=${DB_USERNAME:-oracle}
      - DB_PASSWORD=${DB_PASSWORD:-oracle}
      - DB_SERVICE_NAME=${DB_SERVICE_NAME:-XEPDB1}
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=microservice_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  oracle_data: