export enum EStoreProcedureDB {
  CONSULTA_COMPLEMENTOS = `begin
  mgl_scheme.pkg_consulta_direcciones_v1.prc_consulta_complementos_sp
    (
      PI_TIPO_DIRECCION => :PI_TIPO_DIRECCION,
      PI_DIRECCION_ID => :PI_DIRECCION_ID,
      pi_mz_tipo_nivel1 => :pi_mz_tipo_nivel1,
      pi_mz_valor_nivel1 => :pi_mz_valor_nivel1,
      pi_mz_tipo_nivel2 => :pi_mz_tipo_nivel2,
      pi_mz_valor_nivel2 => :pi_mz_valor_nivel2,
      pi_mz_tipo_nivel3 => :pi_mz_tipo_nivel3,
      pi_mz_valor_nivel3 => :pi_mz_valor_nivel3,
      pi_mz_tipo_nivel4 => :pi_mz_tipo_nivel4,
      pi_mz_valor_nivel4 => :pi_mz_valor_nivel4,
      pi_mz_tipo_nivel5 => :pi_mz_tipo_nivel5,
      pi_mz_valor_nivel5 => :pi_mz_valor_nivel5,
      pi_mz_tipo_nivel6 => :pi_mz_tipo_nivel6,
      pi_mz_valor_nivel6 => :pi_mz_valor_nivel6,
      PI_CP_NIVEL_NIVEL1 => :PI_CP_NIVEL_NIVEL1,
      pi_cp_valor_nivel1 => :pi_cp_valor_nivel1,
      PI_CP_NIVEL_NIVEL2 => :PI_CP_NIVEL_NIVEL2,
      pi_cp_valor_nivel2 => :pi_cp_valor_nivel2,
      PI_CP_NIVEL_NIVEL3 => :PI_CP_NIVEL_NIVEL3,
      pi_cp_valor_nivel3 => :pi_cp_valor_nivel3,
      PI_CP_NIVEL_NIVEL4 => :PI_CP_NIVEL_NIVEL4,
      pi_cp_valor_nivel4 => :pi_cp_valor_nivel4,
      PI_CP_NIVEL_NIVEL5 => :PI_CP_NIVEL_NIVEL5,
      pi_cp_valor_nivel5 => :pi_cp_valor_nivel5,
      PI_CP_NIVEL_NIVEL6 => :PI_CP_NIVEL_NIVEL6,
      pi_cp_valor_nivel6 => :pi_cp_valor_nivel6,
      PI_IT_TIPO_PLACA => :PI_IT_TIPO_PLACA,
      PI_IT_TIPO_VALOR_PLACA => :PI_IT_TIPO_VALOR_PLACA,
      po_codigo => :po_codigo,
      po_descripcion => :po_descripcion,
      PO_COMPLEMENTOS => :PO_COMPLEMENTOS
    );
  end;`,
  CONSULTA_STRUCTURES = `begin
  mgl_scheme.pkg_consulta_direcciones_v1.prc_consulta_dir_bm_it
    (
      pi_codigo_dane => :pi_codigo_dane,
      PI_TIPO_DIRECCION => :PI_TIPO_DIRECCION,
      pi_barrio => :pi_barrio,
      pi_mz_tipo_nivel1 => :pi_mz_tipo_nivel1,
      pi_mz_valor_nivel1 => :pi_mz_valor_nivel1,
      pi_mz_tipo_nivel2 => :pi_mz_tipo_nivel2,
      pi_mz_valor_nivel2 => :pi_mz_valor_nivel2,
      pi_mz_tipo_nivel3 => :pi_mz_tipo_nivel3,
      pi_mz_valor_nivel3 => :pi_mz_valor_nivel3,
      pi_mz_tipo_nivel4 => :pi_mz_tipo_nivel4,
      pi_mz_valor_nivel4 => :pi_mz_valor_nivel4,
      pi_mz_tipo_nivel5 => :pi_mz_tipo_nivel5,
      pi_mz_valor_nivel5 => :pi_mz_valor_nivel5,
      pi_mz_tipo_nivel6 => :pi_mz_tipo_nivel6,
      pi_mz_valor_nivel6 => :pi_mz_valor_nivel6,
      PI_CP_NIVEL_NIVEL1 => :PI_CP_NIVEL_NIVEL1,
      pi_cp_valor_nivel1 => :pi_cp_valor_nivel1,
      PI_CP_NIVEL_NIVEL2 => :PI_CP_NIVEL_NIVEL2,
      pi_cp_valor_nivel2 => :pi_cp_valor_nivel2,
      PI_CP_NIVEL_NIVEL3 => :PI_CP_NIVEL_NIVEL3,
      pi_cp_valor_nivel3 => :pi_cp_valor_nivel3,
      PI_CP_NIVEL_NIVEL4 => :PI_CP_NIVEL_NIVEL4,
      pi_cp_valor_nivel4 => :pi_cp_valor_nivel4,
      PI_CP_NIVEL_NIVEL5 => :PI_CP_NIVEL_NIVEL5,
      pi_cp_valor_nivel5 => :pi_cp_valor_nivel5,
      PI_CP_NIVEL_NIVEL6 => :PI_CP_NIVEL_NIVEL6,
      pi_cp_valor_nivel6 => :pi_cp_valor_nivel6,
      PI_IT_TIPO_PLACA => :PI_IT_TIPO_PLACA,
      PI_IT_TIPO_VALOR_PLACA => :PI_IT_TIPO_VALOR_PLACA,
      po_codigo => :po_codigo,
      po_descripcion => :po_descripcion,
      PO_CONSULTA_DIR => :PO_CONSULTA_DIR
    );
  end;`,
  CONSULTA_DETAIL_ADDRESS = `begin
  mgl_scheme.pkg_consulta_direcciones_v1.prc_consulta_direccion_sp
    (
      pi_codigodanecentropoblado => :pi_codigodanecentropoblado,
      pi_id_tipo_direccion => :pi_id_tipo_direccion,
      pi_dir_princ_alt => :pi_dir_princ_alt,
      pi_barrio => :pi_barrio,
      pi_tipo_via_principal => :pi_tipo_via_principal,
      pi_num_via_principal => :pi_num_via_principal,
      pi_lt_via_principal => :pi_lt_via_principal,
      pi_nl_post_via_p => :pi_nl_post_via_p,
      pi_bis_via_principal => :pi_bis_via_principal,
      pi_cuad_via_principal => :pi_cuad_via_principal,
      pi_tipo_via_generadora => :pi_tipo_via_generadora,
      pi_num_via_generadora => :pi_num_via_generadora,
      pi_lt_via_generadora => :pi_lt_via_generadora,
      pi_nl_post_via_g => :pi_nl_post_via_g,
      pi_letra3g => :pi_letra3g,
      pi_bis_via_generadora => :pi_bis_via_generadora,
      pi_cuad_via_generadora => :pi_cuad_via_generadora,
      pi_placa_direccion => :pi_placa_direccion,
      pi_cp_tipo_nivel1 => :pi_cp_tipo_nivel1,
      pi_cp_tipo_nivel2 => :pi_cp_tipo_nivel2,
      pi_cp_tipo_nivel3 => :pi_cp_tipo_nivel3,
      pi_cp_tipo_nivel4 => :pi_cp_tipo_nivel4,
      pi_cp_tipo_nivel5 => :pi_cp_tipo_nivel5,
      pi_cp_tipo_nivel6 => :pi_cp_tipo_nivel6,
      pi_cp_valor_nivel1 => :pi_cp_valor_nivel1,
      pi_cp_valor_nivel2 => :pi_cp_valor_nivel2,
      pi_cp_valor_nivel3 => :pi_cp_valor_nivel3,
      pi_cp_valor_nivel4 => :pi_cp_valor_nivel4,
      pi_cp_valor_nivel5 => :pi_cp_valor_nivel5,
      pi_cp_valor_nivel6 => :pi_cp_valor_nivel6,
      pi_mz_tipo_nivel1 => :pi_mz_tipo_nivel1,
      pi_mz_tipo_nivel2 => :pi_mz_tipo_nivel2,
      pi_mz_tipo_nivel3 => :pi_mz_tipo_nivel3,
      pi_mz_tipo_nivel4 => :pi_mz_tipo_nivel4,
      pi_mz_tipo_nivel5 => :pi_mz_tipo_nivel5,
      pi_mz_tipo_nivel6 => :pi_mz_tipo_nivel6,
      pi_mz_valor_nivel1 => :pi_mz_valor_nivel1,
      pi_mz_valor_nivel2 => :pi_mz_valor_nivel2,
      pi_mz_valor_nivel3 => :pi_mz_valor_nivel3,
      pi_mz_valor_nivel4 => :pi_mz_valor_nivel4,
      pi_mz_valor_nivel5 => :pi_mz_valor_nivel5,
      pi_mz_valor_nivel6 => :pi_mz_valor_nivel6,
      PI_IT_TIPO_PLACA => :PI_IT_TIPO_PLACA,
      PI_IT_VALOR_PLACA => :PI_IT_VALOR_PLACA,
      po_codigo => :po_codigo,
      po_descripcion => :po_descripcion,
      po_v_response => :po_v_response
    );
    if(:po_v_response IS NULL) then OPEN :po_v_response FOR SELECT * FROM dual WHERE 1 = 0; end if;
  end;`,
  CONSULTA_NEIGHBORHOOD = `begin mgl_scheme.pkg_consulta_direcciones_v1.prc_consulta_barrios_sp
    (
      pi_codigo_dane => :pi_codigo_dane,
      pi_tipo_dir => :pi_tipo_dir,
      po_codigo => :po_codigo,
      po_descripcion => :po_descripcion,
      po_c_barrio => :po_c_barrio
    );
  end;`,
}

export enum ENameCursorDB {
  CONSULTA_COMPLEMENTOS = 'PO_COMPLEMENTOS',
  CONSULTA_STRUCTURES = 'PO_CONSULTA_DIR',
  CONSULTA_DETAIL_ADDRESS = 'po_v_response',
  CONSULTA_NEIGHBORHOOD = 'po_c_barrio',
}

export enum EStoredName {
  CONSULTA_COMPLEMENTOS = 'PKG_CONSULTA_DIRECCIONES_V1.PRC_CONSULTA_COMPLEMENTOS_SP',
  CONSULTA_STRUCTURES = 'PKG_CONSULTA_DIRECCIONES_V1.PRC_CONSULTA_DIR_BM_IT',
  CONSULTA_DETAIL_ADDRESS = 'PKG_CONSULTA_DIRECCIONES_V1.PRC_CONSULTA_DIRECCION_SP',
  CONSULTA_NEIGHBORHOOD = 'PKG_CONSULTA_DIRECCIONES_V1.PRC_CONSULTA_BARRIOS_SP',
}
