export interface IAttributesProduct {
  PartNumber: string,
  AttributeIdentifier?: string,
  ValueIdentifier?: string,
  Value?: string,
  Usage?: string,
  Sequence: string,
  AttributeStoreIdentifier: string,
  Field1: string,
  Field2: string,
  Field3: string,
  AttributeValueField1: string,
  AttributeValueField2: string,
  AttributeValueField3: string,
  AttributeValueDescriptionField1: string,
  AttributeValueDescriptionField2: string,
  AttributeValueDescriptionField3: string,
  AttributeValueDescriptionImage1: string,
  AttributeValueDescriptionImage2: string,
  UnitOfMeasure: string,
  Delete: string,
}