export const DetailAddress_200 = {
  process: 'f3f64980-f5c5-11ed-bf5a-1b56fd041de8',
  success: true,
  status: 200,
  documents: {
    geographicAddressList: {
      geographicAddress: {
        id: 3702884,
        subId: 2108504,
        detailId: 5773307,
        textAddress: 'KR 48 176 11 PI 2',
        strata: 3,
        typeAddrMER: 'CK',
        streetAlt: 'P',
        neighborhood: 'NUEVA ZELANDIA',
        streetType: 'CARRERA',
        streetNr: '48',
        streetSuffix: '',
        streetNlPostViaP: '',
        streetBis: '',
        streetBlockGenerator: '',
      },
      geographicSubAddress: {
        streetTypeGenerator: '',
        streetNrGenerator: '176',
        streetLtGenerator: '',
        streetNlPostViaG: '',
        streetBisGenerator: '',
        streetName: '',
      },
      addressPlate: '11',
      complements: {
        nivel1Type: '',
        nivel2Type: '',
        nivel3Type: '',
        nivel4Type: '',
        nivel5Type: 'PISO',
        nivel6Type: '',
        nivel1Value: '',
        nivel2Value: '',
        nivel3Value: '',
        nivel4Value: '',
        nivel5Value: '2',
        nivel6Value: '',
      },
      alternateGeographicAddress: {
        nivel1Type: '',
        nivel2Type: '',
        nivel3Type: '',
        nivel4Type: '',
        nivel5Type: '',
        nivel6Type: '',
        nivel1Value: '',
        nivel2Value: '',
        nivel3Value: '',
        nivel4Value: '',
        nivel5Value: '',
        nivel6Value: '',
      },
      cadastreId: 's2108504',
      plateTypeIt: '',
      plateValueIt: '',
      geoState: 'M',
      word3G: '',
      indications: '',
    },
  },
  message: 'Execution successfull',
  requestTime: '2023-05-18T21:50:06+00:00',
  responseTime: 10987,
  method: 'POST',
  origen: '/RSServicehomepass/V1/Coverage/detailAddress',
};

export const DetailAddress_201 = {
  process: '60f65fc0-8fd1-11ee-9ab4-01db2c72ce5e',
  success: true,
  status: 201,
  documents: {
    message: 'ERROR',
    code: 1,
    description: 'Direccion no encontrada ',
    source: 'PKG_CONSULTA_DIRECCIONES_V1.PRC_CONSULTA_DIRECCION_SP',
  },
  message: '!Ups¡, No encontamos tu direccion Para continuar con el proceso, permitenos ayudarte y dejanos tus datos dando clic en Aceptar.',
  requestTime: '2023-11-30T17:39:53-05:00',
  method: 'POST',
  origen: '/MSServicehomepass/V1/Coverage/detailAddress',
};

export const DetailAddress_400 = {
  process: '22a371e0-f5c6-11ed-bf5a-1b56fd041de8',
  success: false,
  status: 400,
  documents: ['geographicAddressList.geographicAddress.codeDane should not be empty', 'geographicAddressList.geographicAddress.codeDane must be a string'],
  message: 'Error validación de campos obligatorios.',
  requestTime: '2023-05-18T21:51:25+00:00',
  method: 'POST',
};

export const DetailAddress_500 = {
  process: '6bcfe5b0-f5c6-11ed-bf5a-1b56fd041de8',
  success: false,
  status: 500,
  message:
    '!Ups¡, parece que algo salió mal, inténtalo nuevamente o si prefieres comunícate con nosotros a la línea en Bogotá 7457466 o déjanos tus datos dando clic en Aceptar.',
  requestTime: '2023-05-18T21:53:28+00:00',
  method: 'POST',
};

export const BodyExample = {
  geographicAddressList: {
    geographicAddress: {
      codeDane: '11001000',
      typeAddrMER: 'CK',
      streetAlt: '',
      neighborhood: '',
      streetType: 'CARRERA',
      streetNr: '48',
      streetSuffix: '',
      streetNlPostViaP: '',
      streetBis: '',
      streetBlockGenerator: '',
    },
    geographicSubAddress: {
      streetTypeGenerator: '',
      streetNrGenerator: '176',
      streetLtGenerator: '',
      streetNlPostViaG: '',
      word3G: '',
      streetBisGenerator: '',
      streetName: '',
      plate: '11',
    },
    complements: {
      nivel1Type: '',
      nivel2Type: '',
      nivel3Type: '',
      nivel4Type: '',
      nivel5Type: '',
      nivel6Type: '',
      nivel1Value: '',
      nivel2Value: '',
      nivel3Value: '',
      nivel4Value: '',
      nivel5Value: '',
      nivel6Value: '',
    },
    alternateGeographicAddress: {
      nivel1Type: '',
      nivel2Type: '',
      nivel3Type: '',
      nivel4Type: '',
      nivel5Type: '',
      nivel6Type: '',
      nivel1Value: '',
      nivel2Value: '',
      nivel3Value: '',
      nivel4Value: '',
      nivel5Value: '',
      nivel6Value: '',
    },
    plateTypeIt: '',
    plateValueIt: '',
  },
};

export const BodyFakeAddressNotFound = {
  geographicAddressList: {
    geographicAddress: {
      codeDane: '11001000',
      typeAddrMER: 'CK',
      streetAlt: '',
      neighborhood: '',
      streetType: 'CARRERA',
      streetNr: '48',
      streetSuffix: '',
      streetNlPostViaP: '',
      streetBis: '',
      streetBlockGenerator: '',
    },
    geographicSubAddress: {
      streetTypeGenerator: '',
      streetNrGenerator: '17',
      streetLtGenerator: '',
      streetNlPostViaG: '',
      word3G: '',
      streetBisGenerator: '',
      streetName: '',
      plate: '11',
    },
    complements: {
      nivel1Type: '',
      nivel2Type: '',
      nivel3Type: '',
      nivel4Type: '',
      nivel5Type: '',
      nivel6Type: '',
      nivel1Value: '',
      nivel2Value: '',
      nivel3Value: '',
      nivel4Value: '',
      nivel5Value: '',
      nivel6Value: '',
    },
    alternateGeographicAddress: {
      nivel1Type: '',
      nivel2Type: '',
      nivel3Type: '',
      nivel4Type: '',
      nivel5Type: '',
      nivel6Type: '',
      nivel1Value: '',
      nivel2Value: '',
      nivel3Value: '',
      nivel4Value: '',
      nivel5Value: '',
      nivel6Value: '',
    },
    plateTypeIt: '',
    plateValueIt: '',
  },
};

export const BodyFakeDataValidation = {
  geographicAddressList: {
    geographicAddress: {
      typeAddrMER: 'CK',
      streetAlt: '',
      neighborhood: '',
      streetType: 'CARRERA',
      streetNr: '48',
      streetSuffix: '',
      streetNlPostViaP: '',
      streetBis: '',
      streetBlockGenerator: '',
    },
    geographicSubAddress: {
      streetTypeGenerator: '',
      streetNrGenerator: '17',
      streetLtGenerator: '',
      streetNlPostViaG: '',
      word3G: '',
      streetBisGenerator: '',
      streetName: '',
      plate: '11',
    },
    complements: {
      nivel1Type: '',
      nivel2Type: '',
      nivel3Type: '',
      nivel4Type: '',
      nivel5Type: '',
      nivel6Type: '',
      nivel1Value: '',
      nivel2Value: '',
      nivel3Value: '',
      nivel4Value: '',
      nivel5Value: '',
      nivel6Value: '',
    },
    alternateGeographicAddress: {
      nivel1Type: '',
      nivel2Type: '',
      nivel3Type: '',
      nivel4Type: '',
      nivel5Type: '',
      nivel6Type: '',
      nivel1Value: '',
      nivel2Value: '',
      nivel3Value: '',
      nivel4Value: '',
      nivel5Value: '',
      nivel6Value: '',
    },
    plateTypeIt: '',
    plateValueIt: '',
  },
};
