---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: template-ocp
  labels:
    version: OCP4-1
  annotations:
    openshift.io/display-name: Node.js
    description: MSPrChValGenerate Ecommerce V9
    tags: instalacion,install,nodejs
    iconClass: icon-nodejs
    openshift.io/long-description: Proyecto de contingencia para el catalogo de Ecommerce V9.
    openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/bindable: 'false'
message: |-
  Se han creado los siguientes servicios en su proyecto: ${NAME}.
labels:
  template: ${NAME}
  app: ${NAME}
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: '${NAME}'
    namespace: '${NAMESPACE}'
    annotations:
      description: ${DESCRIPTION}
  spec:
    ports:
      - name: ${PORT}-tcp
        port: ${{PORT}}
        protocol: TCP
        targetPort: ${{PORT}}
    type: ClusterIP
    selector:
      name: '${NAME}'

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: '${NAME}'
    namespace: '${NAMESPACE}'
  data: ${{DATA_CONFIGMAP}}   

- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: '${NAME}'
    namespace: '${NAMESPACE}'
    annotations:
      description: ${DESCRIPTION}
      template.alpha.openshift.io/wait-for-ready: 'true'
    labels:
      app: '${NAME}'
      legado: ${LEGADO}
      proyecto: ${PROYECTO}
      subproyecto: ${SUBPROYECTO}
      tecnologia: ${TECNOLOGIA}
  spec:
    replicas: '${{MIN_REPLICAS}}'
    strategy:
      type: Rolling
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: "${MAX_SURGE}"
        maxUnavailable: "${MAX_UNAVAILABLE}"
        timeoutSeconds: 300
        updatePeriodSeconds: 1
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - ${NAME}
        from:
          kind: ImageStreamTag
          name: '${NAME}:${VERSION}'
    - type: ConfigChange
    selector:
      name: '${NAME}'
    template:
      metadata:
        name: '${NAME}'
        labels:
          name: '${NAME}'
      spec:
        automountServiceAccountToken: false
        containers:
        - name: ${NAME}
          image: ""
          ports:
            - containerPort: ${{PORT}}
              protocol: "TCP"
          type: "Recreate"
          resources:
            limits:
              cpu: "${CPU_LIMIT}"
              memory: "${MEMORY_LIMIT}"
            requests:
              cpu: "${CPU_REQUEST}"
              memory: "${MEMORY_REQUEST}"
          envFrom:
            - configMapRef:
                name: '${NAME}'
            - secretRef:
                name: '${NAME}'
          readinessProbe:
            tcpSocket:
              port: ${{PORT}}
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 5

- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    name: ${NAME}
    namespace: '${NAMESPACE}'
  spec:
    minReplicas: ${{MIN_REPLICAS}} 
    maxReplicas: ${{MAX_REPLICAS}}
    behavior:
      scaleUp:
        stabilizationWindowSeconds: 120
      scaleDown:
        stabilizationWindowSeconds: 120
    scaleTargetRef:
      apiVersion: apps.openshift.io/v1 
      kind: DeploymentConfig 
      name: ${NAME}
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: ${{CPU_TARGET_AVERAGE_UTILIZATION}}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: ${{MEMORY_TARGET_AVERAGE_UTILIZATION}}

parameters:
- name: NAME
  description: El nombre asignado a todos los objetos frontend definidos en esta plantilla.
  value: msprchvalgenerate
- name: NAMESPACE 
  description: Nombre del namespace
  required: true
  value: ecommercev9dev
- name: VERSION 
  description: versión de la aplicación, actualmente se define versión latest para todos los despliegues, en futuro se utilizará un método de versionamiento. 
  value: latest
- name: MEMORY_LIMIT
  description: Cantidad máxima de memoria que puede utilizar el contenedor.
  value: 550Mi
- name: CPU_LIMIT
  description: Cantidad máxima de procesador que puede utilizar el contenedor.
  value: 250m
- name: MIN_REPLICAS
  description: Cantidad minima de pods.
  value: '1'
- name: MAX_REPLICAS
  description: Cantidad maxima de pods.
  value: '1'
- name: CPU_TARGET_AVERAGE_UTILIZATION 
  description: El porcentaje de la CPU solicitada que cada pod debería usar idealmente.
  value: '80'
- name: MEMORY_TARGET_AVERAGE_UTILIZATION
  description: El porcentaje de memoria solicitada que cada pod debería usar idealmente.
  value: '100'
- name: MAX_SURGE
  description: Número máximo de pods que se pueden programar por encima del número original de pods.
  value: 20%
- name: MAX_UNAVAILABLE
  description: número máximo de pods que pueden no estar disponibles durante la actualización.
  value: 0%
- name: MEMORY_REQUEST
  description: Cantidad máxima de memoria que puede utilizar el contenedor.
  value: 10Mi
- name: CPU_REQUEST
  description: Cantidad máxima de procesador que puede utilizar el contenedor.
  value: 10m
- name: DESCRIPTION 
  description: Descripción de la aplicación. 
  value: Esta plantilla define los recursos necesarios para una aplicación NestJS, incluida una configuración de compilación y una configuración de implementación de la aplicación. No incluye una base de datos.
- name: PORT 
  description: Puerto a usar para la exposición de la aplicación. 
  value: "8080"
- name: PROYECTO 
  description: Etiqueta del nombre de proyecto 
  value: 'ecommercev9dev' 
- name: SUBPROYECTO 
  description: Etiqueta del nombre de sub-proyecto, si no aplica se define el mismo nombre del proyecto. 
  value: 'ecommercev9dev' 
- name: LEGADO
  description: Etiqueta de legados definidos para el proyecto, estos van separados por guion bajo "_" (LEGADOA_LEGADOB). 
  value: 'OMNSERVICE_MONGO_MONGOCATALOG_MONGODISPONIBILITY'
- name: TECNOLOGIA 
  description: Etiqueta de la tecnología a usar, los valores validos serán= SpringBoot-Maven, NodeJS, NestJS. 
  value: NestJS
- name: DATA_CONFIGMAP
  description: "Variables de entorno a usar en deployment. Ejm.= {'ENV_1': 'Valor_1', 'ENV_2': 'Valor_2', ....}"
  value: |
    {
      "API_MAPPING": "/MSPrChValGenerate",
      "API_VERSION": "V1",
      "CONTINGENCY_CONTROLLER": "/contingency",
      "LOG_LEVEL": "ALL",
      "HTTP_TIMEOUT": "10000",
      "HTTP_HEADERS_TIMEOUT": "50000",
      "SFTP_MODULE_HOST": "172.22.94.68",
      "SFTP_MODULE_PORT": "22",
      "SFTP2_MODULE_HOST": "172.22.94.68",
      "SFTP2_MODULE_PORT": "22",
      "CRON_EXECUTION_TYT_PRICESATTRIBUTES": "0 0 0 1 1 *",
      "CRON_EXECUTION_MOBILE_PRICESATTRIBUTES": "0 0 0 1 1 *",
      "CRON_EXECUTION_HOMES_PRICESATTRIBUTES": "0 0 0 1 1 *",
      "PAGINATION_DB": "150",
      "SPECIFICATION_SUBTYPE": "Telefono",
      "SPECIFICATION_SUBTYPEPOS": "Movil",
      "SPECIFICATION_SUBTYPEPRE": "Movil",
      "OMNSERVICE": "https://msproductinventorymanage-omnqa.apps.r05oof71.eastus2.aroapp.io/products/Catalog",
      "MONGO": "mongodb://bd_user:bd_password@pl-1-eastus2-azure.qremx.mongodb.net:1027,pl-1-eastus2-azure.qremx.mongodb.net:1028,pl-1-eastus2-azure.qremx.mongodb.net:1029/DBPRTPRODUCTOFFERING_DE?replicaSet=atlas-89o7hw-shard-0&ssl=true&authSource=admin",
      "MONGOCATALOG": "mongodb://bd_user:bd_password@pl-1-eastus2-azure.qremx.mongodb.net:1027,pl-1-eastus2-azure.qremx.mongodb.net:1028,pl-1-eastus2-azure.qremx.mongodb.net:1029/DBPRTCATALOG_DE?replicaSet=atlas-89o7hw-shard-0&ssl=true&authSource=admin",
      "MONGODISPONIBILITY": "mongodb://bd_user:bd_password@pl-1-eastus2-azure.qremx.mongodb.net:1027,pl-1-eastus2-azure.qremx.mongodb.net:1028,pl-1-eastus2-azure.qremx.mongodb.net:1029/DBPRTDisponibility_DE?replicaSet=atlas-89o7hw-shard-0&ssl=true&authSource=admin",
      "DBNAMEPRTOFFERING": "DBPRTPRODUCTOFFERING_DE",
      "DBNAMECATALOG": "DBPRTCATALOG_DE",
      "DBNAMECATALOGDISPONIBILITYFILE": "COLPRTDisponibilityFile",
      "ELASTIC_APM_SERVICE_NAME": "msprchvalgenerate",
      "ELASTIC_APM_SERVER_URL": "http://100.69.7.130:8200",
      "ELASTIC_APM_ENVIRONMENT": "ecommercev9dev",
      "ELASTIC_APM_CAPTURE_BODY": "all",
      "ELASTIC_APM_CAPTURE_HEADERS": "true",
      "ELASTIC_APM_LOG_LEVEL": "off",
      "ELASTIC_APM_ACTIVE": "true",
      "LOG_TRAZABILITY": "true"
    }
